import {el,button} from './editor-dom.js?v=55';
import {icon} from './control-icons.js?v=55';
import {showDialog} from './dialogs.js?v=55';
export function setExpandButton(control,expanded){control.replaceChildren(icon([{d:expanded?'M3 3l6 6M3 9h6V3M21 21l-6-6m0 6v-6h6M21 3l-6 6m6 0h-6V3M3 21l6-6m-6 0h6v6':'M9 9 3 3m0 6V3h6M15 15l6 6m0-6v6h-6M15 9l6-6m-6 0h6v6M9 15l-6 6m6 0H3v-6',fill:'none',stroke:'currentColor','stroke-width':1.5,'stroke-linecap':'round','stroke-linejoin':'round'}]));control.setAttribute('aria-label',expanded?'Restore card view size':'Double card view size');control.setAttribute('aria-pressed',String(expanded));control.title=expanded?'Restore size':'Double size';}
export function fullscreenButton(action){const b=button('',action,'card-fullscreen-button');b.setAttribute('aria-label','Full screen card');b.title='Full screen card';b.append(icon([{d:'M9 3H3v6M15 3h6v6M21 15v6h-6M3 15v6h6',fill:'none',stroke:'currentColor','stroke-width':1.7,'stroke-linecap':'round','stroke-linejoin':'round'}]));return b;}
// Fill the existing DM document; never replace its browser fullscreen element.
export function openCardFullscreen({title,pages=[],text='',index=0}){if(!pages.length&&!text)return;const dialog=el('dialog',undefined,'card-fullscreen-dialog'),heading=el('div',undefined,'reference-heading'),body=el('div',undefined,'card-fullscreen-body'),count=el('span',undefined,'card-page-count');let page=Math.max(0,Math.min(pages.length-1,index));dialog.setAttribute('aria-label',`${title} full screen`);const prev=button('←',()=>step(-1)),next=button('→',()=>step(1)),exit=button('',()=>dialog.close(),'card-fullscreen-exit');prev.setAttribute('aria-label','Previous card');next.setAttribute('aria-label','Next card');setExpandButton(exit,true);exit.setAttribute('aria-label','Exit full screen card');exit.title='Exit full screen card';heading.append(el('h2',title));if(pages.length>1)heading.append(prev,count,next);heading.append(exit);dialog.append(heading,body);
 function render(){body.replaceChildren();count.textContent=`${page+1} / ${pages.length}`;if(pages.length){const image=el('img');image.src=pages[page].src;image.alt=`${title}, card ${page+1}`;body.append(image);}else body.append(el('div',text,'fullscreen-stat-text'));body.scrollTop=0;}
 function step(delta){page=(page+delta+pages.length)%pages.length;render();}
 dialog.addEventListener('keydown',e=>{if(pages.length>1&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();e.stopPropagation();step(e.key==='ArrowLeft'?-1:1);}});dialog.addEventListener('close',()=>dialog.remove(),{once:true});document.body.append(dialog);showDialog(dialog);render();return dialog;
}
