import {statIcon} from './control-icons.js?v=40';
import {tokenGallery} from './token-gallery.js?v=40';
import {createMemberStrip} from './member-strip.js?v=40';
import {editStatCard} from './stat-card-editor.js?v=40';
import {groupSelection} from './group-selection.js?v=40';
import {registerMenu,openMenu,closeMenu} from './main-menu.js?v=40';
import {conditionIcon} from './condition-icons.js?v=40';
import {shortcutAction,isTextEntry} from './keyboard.js?v=40';
import {CONDITIONS,MONSTERS,normalizeMember,syncCampaign,applyGroup,deleteGroup,combatants,initiativeOrder,stepTurn,patchMember,parseInitiative,changeHP,fiveFeet,resetInitiative} from './combat-state.js?v=40';
import {PORTRAITS,PARTY_CHOICES,formation} from './encounter-state.js?v=40';
import {setFace,portraitStyle} from './token-portraits.js?v=40';
const $=id=>document.getElementById(id);
export function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
export function button(text,fn,cls){const b=el('button',text,cls);b.type='button';if(fn)b.addEventListener('click',fn);return b;}
export function badgeNodes(member){const container=el('span',undefined,'condition-badges');for(const id of member.conditions||[]){const c=CONDITIONS.find(c=>c[0]===id);if(!c)continue;const b=el('span',undefined,'condition-badge');b.title=c[2];b.setAttribute('aria-label',c[2]);b.append(conditionIcon(id));container.append(b);}for(const letter of member.letters||[]){const b=el('span',letter,'condition-badge');b.title=`Marker ${letter}`;b.setAttribute('aria-label',b.title);container.append(b);}return container;}
function imageFor(member){const img=el('img');img.alt='';img.width=img.height=40;img.draggable=false;setFace(img,member);return img;}
function input(value,label,change,type='text'){const field=el('input');field.type=type;field.value=value??'';field.setAttribute('aria-label',label);field.addEventListener('input',()=>change(field.value));return field;}
function labeled(label,field){const wrap=el('label',label,'field-label');wrap.append(field);return wrap;}
export function createCombatUI({map,player,getState,commit,announce,getPresentation,advanceStory,showStat,showAssigned,locate}){
  const stage=$('map-stage'),overlay=el('div',undefined,player?'player-initiative':'initiative-preview');overlay.id='initiative-overlay';stage.append(overlay);
  const rows=new Map();let panel,list,left,signature='',overlayDrag=null,lastActive=null,lastOrder='';
  if(!player){
    left=el('section',undefined,'combat-roster');left.id='combat-roster';document.querySelector('.encounter-heading').after(left);
    panel=el('aside',undefined,'initiative-panel');panel.id='initiative-panel';panel.tabIndex=0;panel.setAttribute('aria-label','Initiative turn order');const heading=el('div',undefined,'initiative-heading');heading.append(el('h2','Initiative'),button('↑',()=>advance(-1)),button('↓',()=>advance(1)));heading.children[1].setAttribute('aria-label','Previous turn');heading.children[2].setAttribute('aria-label','Next turn');list=el('div');list.id='initiative-list';
    const visibility=el('label',undefined,'check-label');const check=input('', 'Show player order',()=>{const s=getState();commit({...s,initiativeOverlay:{...s.initiativeOverlay,visible:check.checked}},'Player order visibility updated.');},'checkbox');check.id='initiative-visible';visibility.append(check,document.createTextNode('Player order'));panel.append(heading,visibility,list);document.querySelector('.workspace').append(panel);
    document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.target.closest('.reference-suite'))return;const field=isTextEntry(e.target)?e.target:null,hp=field?.hasAttribute('data-hp-input');const action=shortcutAction({key:e.key,typing:!!field,hp,story:getPresentation?.().mode==='story',conditions:!!document.querySelector('.token-status-editor'),modal:!!document.querySelector('dialog[open],.dice-panel:not([hidden])'),meta:e.metaKey,ctrl:e.ctrlKey,alt:e.altKey,shift:e.shiftKey,composing:e.isComposing});if(!action)return;if(action==='next-story'){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat)advanceStory?.();}else if(['next-turn','previous-turn'].includes(action)){if(!initiativeOrder(getState()).length)return;e.preventDefault();e.stopImmediatePropagation();advance(action==='next-turn'?1:-1);}else if(action==='damage'||action==='heal'){e.preventDefault();e.stopImmediatePropagation();field.closest('.turn-row').querySelector(`[data-hp-action="${action}"]`).click();}else if(action==='undo'||action==='redo'){e.preventDefault();e.stopImmediatePropagation();$(action).click();}},true);

    overlay.tabIndex=0;overlay.setAttribute('aria-label','Player initiative position. Drag to place.');
    overlay.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.stopPropagation();e.preventDefault();overlayDrag={id:e.pointerId,x:e.clientX,y:e.clientY,start:{...getState().initiativeOverlay},rect:stage.getBoundingClientRect()};overlay.setPointerCapture(e.pointerId);});
    overlay.addEventListener('pointermove',e=>{if(!overlayDrag)return;const d=overlayDrag;overlay.style.left=`${Math.max(0,Math.min(.8,d.start.x+(e.clientX-d.x)/d.rect.width))*100}%`;overlay.style.top=`${Math.max(0,Math.min(.85,d.start.y+(e.clientY-d.y)/d.rect.height))*100}%`;});
    overlay.addEventListener('pointerup',()=>{if(!overlayDrag)return;overlayDrag=null;const s=getState();commit({...s,initiativeOverlay:{...s.initiativeOverlay,x:parseFloat(overlay.style.left)/100,y:parseFloat(overlay.style.top)/100}},'Player order moved.');});
    overlay.addEventListener('pointercancel',()=>{overlayDrag=null;render();});

  }
  function focusAmount(id){const field=rows.get(id)?.querySelector('[data-hp-input]');if(field){field.focus({preventScroll:true});field.select();}else if(document.activeElement?.hasAttribute('data-hp-input'))document.activeElement.blur();}
  function advance(delta){const next=stepTurn(getState(),delta);commit(next,delta<0?'Previous turn.':'Next turn.');focusAmount(next.turnId);}
  function rosterSection(title,members,monster){const section=el('div',undefined,'static-roster');const heading=el('div',undefined,'roster-heading'),reset=button('Reset',()=>commit(resetInitiative(getState(),monster),`${monster?'Encounter':'Party'} initiative scores reset.`),'reset-initiative');reset.dataset.reset=monster?'encounter':'party';reset.setAttribute('aria-label',`Reset ${monster?'encounter':'party'} initiative scores`);reset.title='Clear initiative scores';heading.append(el('h3',title),reset);section.append(heading);if(!members.length)section.append(el('p',monster?'Choose an encounter above.':'Add players in Party.','tool-hint'));
    for(const m of members){const row=el('div',undefined,'combat-roster-row');row.dataset.member=m.id;const face=button('',()=>monster?showStat(combatants(getState()).find(p=>p.id===m.id)):showAssigned(m.id),'roster-portrait');face.setAttribute('aria-label',monster?`Open ${m.name} stat card`:`Open ${m.name} assigned spells`);face.append(imageFor(m));if(monster&& (m.statCard||m.statText)){const badge=el('span',undefined,'portrait-stat');badge.append(statIcon());face.append(badge);}const name=button(m.name,()=>{score.focus({preventScroll:true});score.select();},'roster-name');name.setAttribute('aria-label',`Initiative for ${m.name}: focus score`);name.addEventListener('dblclick',()=>locate(m.id));
      const score=input(m.initiative,`Initiative for ${m.name}`,v=>{const parsed=parseInitiative(v);if(/^-$|^-?\d+[.,]$/.test(v))return;if(v.trim()&&parsed===null){score.value=combatants(getState()).find(p=>p.id===m.id)?.initiative??'';announce('Enter a number, using a dot or comma for decimals.');return;}commit(patchMember(getState(),m.id,{initiative:parsed}),'Initiative updated.');});score.addEventListener('blur',()=>score.value=combatants(getState()).find(p=>p.id===m.id)?.initiative??'');score.addEventListener('keydown',e=>{if(!['Enter','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)||e.isComposing||e.ctrlKey||e.metaKey||e.altKey)return;e.preventDefault();e.stopPropagation();const fields=[...left.querySelectorAll('.initiative-input')],delta=['ArrowUp','ArrowLeft'].includes(e.key)?-1:1,next=fields[(fields.indexOf(score)+delta+fields.length)%fields.length];next?.focus({preventScroll:true});next?.select();if(next){const container=left.closest('.dm-panel'),r=next.getBoundingClientRect(),p=container.getBoundingClientRect();if(r.top<p.top)container.scrollTop-=p.top-r.top;else if(r.bottom>p.bottom)container.scrollTop+=r.bottom-p.bottom;}});score.inputMode='decimal';score.placeholder='—';score.className='initiative-input';
      row.append(face,name,score);if(monster){const visible=input('',`Show ${m.name} to players`,()=>commit(patchMember(getState(),m.id,{visible:visible.checked}),'Monster visibility updated.'),'checkbox');visible.checked=m.visible;visible.title='Visible to players';row.append(visible);}section.append(row);
    }return section;
  }
  function render(){const s=getState(),order=initiativeOrder(s),active=player?s.turnId:(order.some(m=>m.id===s.turnId)?s.turnId:order[0]?.id),players=initiativeOrder(s,true);
    if(!overlayDrag){overlay.style.left=`${s.initiativeOverlay.x*100}%`;overlay.style.top=`${s.initiativeOverlay.y*100}%`;}
    overlay.hidden=!s.initiativeOverlay.visible||!players.length;
    overlay.replaceChildren();if(!player)overlay.append(el('span','Player order · drag to place','overlay-kicker'));
    for(const m of players){const row=el('div',undefined,`public-turn${m.id===active?' current':''}`);row.append(badgeNodes(m),imageFor(m),el('span',m.name));overlay.append(row);}
    if(player)return;
    $('initiative-visible').checked=s.initiativeOverlay.visible;
    const sig=JSON.stringify([s.campaign?.activeParty,s.campaign?.activeEncounter,s.campaign?.parties.map(g=>[g.id,g.name]),s.campaign?.encounters.map(g=>[g.id,g.name]),s.roster.map(({initiative,position,hp,conditions,letters,stack,...m})=>m),s.monsters.map(({initiative,position,hp,conditions,letters,stack,...m})=>m)]);if(sig!==signature){signature=sig;const p=s.campaign?.parties.find(p=>p.id===s.campaign.activeParty),g=s.campaign?.encounters.find(g=>g.id===s.campaign.activeEncounter);left.replaceChildren(rosterSection(p?.name||'Party',s.roster,false),rosterSection(g?.name||'Encounter',s.monsters||[],true));}
    for(const b of left.querySelectorAll('[data-reset]'))b.disabled=!(b.dataset.reset==='encounter'?s.monsters:s.roster).some(m=>m.initiative!==null);
    for(const row of left.querySelectorAll('[data-member]')){const m=combatants(s).find(m=>m.id===row.dataset.member),field=row.querySelector('.initiative-input');if(m&&field!==document.activeElement)field.value=m.initiative??'';}
    for(const[id,row]of rows)if(!order.some(m=>m.id===id)){row.remove();rows.delete(id);}
    let empty=list.querySelector('.initiative-empty');if(!order.length){if(!empty)list.append(el('p','No initiative scores yet.','initiative-empty tool-hint'));}else empty?.remove();
    for(const m of order){let row=rows.get(m.id);if(!row){row=el('div',undefined,'turn-row');row.dataset.turn=m.id;row.addEventListener('click',e=>{if(!e.target.closest('button,input,select,textarea,a'))row.querySelector('.turn-select').click();});const header=el('div',undefined,'turn-main'),portrait=button('',()=>{const current=combatants(getState()).find(v=>v.id===m.id);current.monster?showStat(current,'right'):showAssigned(m.id,'right');},'turn-portrait');portrait.append(imageFor(m));const badge=el('span',undefined,'portrait-stat');badge.append(statIcon());portrait.append(badge);header.append(portrait);const select=button('',()=>{commit({...getState(),turnId:m.id},'Turn selected.');focusAmount(m.id);},'turn-select');const b=el('span',undefined,'turn-conditions'),name=el('span',undefined,'turn-name');select.append(b,name);header.append(select);row.append(header);if(m.monster){const hp=el('span',undefined,'hp-display'),box=el('div',undefined,'hp-adjust');const amount=input('',`Damage or healing for ${m.name}`,()=>{},'number');amount.min=0;amount.step=1;amount.placeholder='0';amount.dataset.hpInput=m.id;amount.addEventListener('focus',()=>amount.select());const adjust=heal=>{const member=getState().monsters.find(p=>p.id===m.id);commit(patchMember(getState(),m.id,changeHP(member,amount.value,heal)),`${m.name} HP updated.`);amount.value='';amount.focus({preventScroll:true});};const damage=button('',()=>adjust(false)),heal=button('',()=>adjust(true));damage.dataset.hpAction='damage';heal.dataset.hpAction='heal';const cross=document.createElementNS('http://www.w3.org/2000/svg','svg');cross.setAttribute('viewBox','0 0 24 24');cross.setAttribute('aria-hidden','true');cross.classList.add('heal-icon');const crossPath=document.createElementNS('http://www.w3.org/2000/svg','path');crossPath.setAttribute('d','M9 2H15V9H22V15H15V22H9V15H2V9H9Z');cross.append(crossPath);heal.append(cross);const sword=document.createElementNS('http://www.w3.org/2000/svg','svg');sword.setAttribute('viewBox','0 0 24 24');sword.setAttribute('aria-hidden','true');sword.classList.add('sword-icon');const blade=document.createElementNS('http://www.w3.org/2000/svg','path');blade.setAttribute('d','M14 3h7v7L10 18l-4-4L14 3ZM4 12l8 8M7 17l-4 4M2 19l3 3');sword.append(blade);damage.append(sword);damage.setAttribute('aria-label',`Damage ${m.name}`);heal.setAttribute('aria-label',`Heal ${m.name}`);damage.title="Apply damage";heal.title="Apply healing";box.append(hp,damage,amount,heal);row.append(box);}rows.set(m.id,row);}
      row.classList.toggle('current',active===m.id);row.classList.toggle('monster-turn',!!m.monster);const select=row.querySelector('.turn-select'),portrait=row.querySelector('.turn-portrait');select.setAttribute('aria-label',`${m.name}, initiative ${m.initiative}`);row.querySelector('.turn-conditions').replaceChildren(badgeNodes(m));setFace(portrait.firstElementChild,m);portrait.setAttribute('aria-label',m.monster?`Open ${m.name} stat card`:`Open ${m.name} assigned spells`);portrait.querySelector('.portrait-stat').hidden=!m.monster||!(m.statCard||m.statText);row.querySelector('.turn-name').textContent=m.name;if(m.monster)row.querySelector('.hp-display').textContent=`HP ${m.hp}/${m.maxHp}`;const index=order.indexOf(m);if(list.children[index]!==row)list.insertBefore(row,list.children[index]||null);
    }
    const orderKey=order.map(m=>m.id).join(':');if(active!==lastActive||orderKey!==lastOrder){lastActive=active;lastOrder=orderKey;const row=rows.get(active);if(row){const r=row.getBoundingClientRect(),p=panel.getBoundingClientRect();if(r.top<p.top)panel.scrollTop-=p.top-r.top;else if(r.bottom>p.bottom)panel.scrollTop+=r.bottom-p.bottom;}}
  }
  return {render};
}

export function createLibraries({map,getState,commit,announce}){
  for(const kind of ['party','encounter']){
    const monster=kind==='encounter',title=monster?'Encounter':'Party',key=monster?'encounters':'parties',active=monster?'activeEncounter':'activeParty';let selected=null,memberId=null,librarySource='factory',selectedUser=null;const selection=groupSelection();const error=el('p','','save-error');error.setAttribute('role','alert');
    const open=button(`${title} ⌄`,()=>show(),'map-picker');open.id=`open-${kind}-library`;open.setAttribute('aria-haspopup','dialog');document.querySelector('.site-identity').append(open);
    const dialog=el('section',undefined,'library-dialog');dialog.id=`${kind}-dialog`;const heading=el('div',undefined,'map-menu-heading');const close=button('×',()=>closeMenu(),'quiet');close.setAttribute('aria-label',`Close ${kind} menu`);heading.append(el('h2',title),close);
    const layout=el('div',undefined,'library-layout'),groups=el('section',undefined,'library-groups'),members=el('section',undefined,'library-members');layout.append(groups,members);const footer=el('div',undefined,'dialog-actions');const apply=button('Done',()=>{if(selected&&getState().campaign?.[active]!==selected)commit(applyGroup(getState(),kind,selected),`${title} activated.`);closeMenu();},'primary');const hint=el('p','','library-save-hint');const remove=button(`Delete ${kind}`,()=>{let next=getState();for(const id of selection.ids)next=deleteGroup(next,kind,id);commit(next,`${title} groups deleted. Undo restores them.`);selected=null;memberId=null;selection.reset();render();},'delete-group');footer.append(remove,apply);dialog.append(heading,error,hint,layout,footer);document.body.append(dialog);
    const memberStrip=createMemberStrip({monster,onSelect:id=>{memberId=id;selectedUser=null;render();},onRemove:id=>editGroup(g=>({...g,members:g.members.filter(m=>m.id!==id)})),onRemoveMany:ids=>editGroup(g=>({...g,members:g.members.filter(m=>!ids.includes(m.id))})),onStat:async id=>{const groupId=selected,m=syncCampaign(getState()).campaign[key].find(g=>g.id===groupId)?.members.find(m=>m.id===id);if(!m)return;const patch=await editStatCard(m);if(patch)editGroup(g=>({...g,members:g.members.map(v=>v.id===id?{...v,...patch}:v)}),'Stat card updated.',true,groupId);}});
    function editGroup(fn,message='',redraw=true,groupId=selected){const s=syncCampaign(getState()),list=s.campaign[key].map(g=>g.id===groupId?fn(g):g),campaign={...s.campaign,[key]:list};let next={...s,campaign};if(campaign[active]===groupId)next={...next,[monster?'monsters':'roster']:list.find(g=>g.id===groupId)?.members||[]};commit(next,message);if(redraw)render();else{const updated=list.find(g=>g.id===selected);for(const b of groups.querySelectorAll('[data-group]')){const g=list.find(g=>g.id===b.dataset.group);if(g)b.textContent=`${g.name}${g.id===campaign[active]?' · Active':''}`;}for(const b of members.querySelectorAll('[data-member-id]')){const m=updated?.members.find(m=>m.id===b.dataset.memberId);if(m)b.lastElementChild.textContent=m.name;}}}
    function addGroup(){const id=crypto.randomUUID(),s=syncCampaign(getState());if(s.campaign[key].length>=20){announce('Up to 20 groups per library.');return;}selected=id;selection.reset(id);memberId=null;commit({...s,campaign:{...s.campaign,[key]:[...s.campaign[key],{id,name:title,members:[]}]}},`${title} created.`);render();}
    function render(){const s=syncCampaign(getState()),items=s.campaign[key];if(!items.some(g=>g.id===selected))selected=s.campaign[active]||items[0]?.id;selection.prune(items.map(g=>g.id),selected);const group=items.find(g=>g.id===selected);groups.replaceChildren(el('h3',monster?'Encounters':'Parties'),button(`+ New ${kind}`,addGroup));
      for(const g of items){const b=button(`${g.name}${g.id===s.campaign[active]?' · Active':''}`,e=>{selected=selection.click(g.id,e,items.map(g=>g.id));memberId=null;render();},'library-group');b.dataset.group=g.id;b.setAttribute('aria-pressed',selection.has(g.id));b.classList.toggle('editing-group',g.id===selected);groups.append(b);}members.replaceChildren();const isActive=group?.id===s.campaign[active];remove.disabled=!selection.ids.length;remove.textContent=selection.ids.length>1?`Delete ${selection.ids.length} ${monster?'encounters':'parties'}`:`Delete ${kind}`;apply.disabled=false;apply.textContent=!group||isActive?'Done':`Activate ${kind}`;hint.textContent='';if(!group){members.append(el('p','Create a group to add its members.','tool-hint'));return;}
      const name=input(group.name,`${title} name`,v=>editGroup(g=>({...g,name:v.trim().slice(0,48)||title}),'',false));name.maxLength=48;const actions=el('div',undefined,'library-member-actions');actions.append(labeled(`${title} name`,name),button(monster?'+ Add monster':'+ Add player',()=>{if(group.members.length>=60){announce('Up to 60 members per group.');return;}memberId=crypto.randomUUID();const point=formation(map,getState().party,60)[group.members.length]||getState().party;editGroup(g=>({...g,members:[...g.members,normalizeMember({id:memberId,name:monster?'Goblin':`Player ${g.members.length+1}`,portrait:monster?0:PARTY_CHOICES[g.members.length%PARTY_CHOICES.length].id,position:point,visible:false},0,monster)]}));}));const memberControls=el('div',undefined,'member-add-remove');memberControls.append(actions.lastElementChild,memberStrip.removeSelected);actions.append(memberControls);members.append(actions);
      if(!group.members.some(m=>m.id===memberId))memberId=group.members[0]?.id;
      members.append(memberStrip.render(group.members,memberId,selected));
      if(!group.members.some(m=>m.id===memberId))memberId=group.members[0]?.id;const m=group.members.find(m=>m.id===memberId);if(!m){members.append(el('p',`Add ${monster?'a monster':'a player'} to this group.`,'tool-hint'));return;}
      const patch=(p,redraw=true)=>editGroup(g=>({...g,members:g.members.map(v=>v.id===memberId?{...v,...p}:v)}),'',redraw);const fields=el('div',undefined,'member-fields');const naming=input(m.name,monster?'Monster name':'Player name',v=>patch({name:v.trim().slice(0,32)||'Unnamed'},false));naming.maxLength=32;fields.append(labeled('Name',naming));
      if(monster){
        const currentMember=()=>syncCampaign(getState()).campaign[key].find(g=>g.id===selected).members.find(v=>v.id===memberId);
        const size=input(m.size,'Token size in feet',v=>patch({size:fiveFeet(v)},false),'number');size.min=5;size.max=200;size.step=5;size.addEventListener('blur',()=>size.value=fiveFeet(size.value));
        const current=input(m.hp,'Current HP',v=>patch({hp:Math.max(0,Math.min(currentMember().maxHp,Math.round(Number(v)||0)))},false),'number');current.disabled=m.hpLinked!==false;
        const maximum=input(m.maxHp,'Maximum HP',v=>{const maxHp=Math.max(0,Math.min(100000,Math.round(Number(v)||0))),member=currentMember(),hp=member.hpLinked!==false?maxHp:Math.min(member.hp,maxHp);patch({maxHp,hp},false);current.value=hp;},'number');
        const link=button('',()=>{const member=currentMember(),hpLinked=member.hpLinked===false;patch({hpLinked,...(hpLinked?{hp:member.maxHp}:{})});},'hp-link');link.setAttribute('aria-label',m.hpLinked===false?'Link Current HP to Max HP':'Unlink Current HP from Max HP');link.setAttribute('aria-pressed',m.hpLinked!==false);link.title=m.hpLinked===false?'Link HP':'Unlink HP';link.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><path d="m9 15 6-6M8 17l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0M16 7l1-1a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"/></svg>';
        maximum.min=current.min=0;maximum.step=current.step=1;fields.append(labeled('Size · ft',size),labeled('Max HP',maximum),link,labeled('Current HP',current));
      }
      members.append(fields);
      const applyAvatar=changes=>{memberStrip.highlight(memberId);patch(changes);};
      members.append(tokenGallery({kind:monster?'encounter':'party',mode:librarySource,setMode:value=>librarySource=value,selected:selectedUser||s.campaign.userTokens[monster?'encounter':'party'].find(t=>t.asset===m.avatar)?.id,setSelected:id=>selectedUser=id,getState,commit,onApply:token=>applyAvatar({avatar:token.asset}),onRefresh:render,error,factory:()=>{const grid=el('div',undefined,`portrait-options library-portraits${monster?'':' paired-portraits'}`);(monster?MONSTERS.map((name,id)=>({name,id})):PARTY_CHOICES).forEach(({name,id:index})=>{const b=button('',()=>applyAvatar({portrait:index,avatar:null,...(monster&&MONSTERS.includes(syncCampaign(getState()).campaign[key].find(g=>g.id===selected).members.find(v=>v.id===memberId).name)?{name}: {})}),'portrait-option');b.setAttribute('aria-label',name);b.title=name;b.setAttribute('aria-pressed',m.portrait===index&&!m.avatar);const face=el('span',undefined,'portrait-thumb');portraitStyle(face,index,monster);b.append(face);grid.append(b);});return grid;}}));
    }
    registerMenu(kind,dialog,{onShow:fresh=>{error.textContent='';if(fresh){librarySource='factory';selectedUser=null;selected=getState().campaign?.[active];selection.reset(selected);}render();}});
    function show(){openMenu(kind);}
    if(!monster)document.addEventListener('edit-party-member',e=>{memberId=e.detail;show();});
  }
}
