import {CONDITIONS,MONSTERS,normalizeMember,syncCampaign,applyGroup,combatants,initiativeOrder,stepTurn,patchMember,parseInitiative,changeHP,fiveFeet} from './combat-state.js?v=16';
import {PORTRAITS,formation} from './encounter-state.js?v=16';
import {setFace,portraitStyle} from './token-portraits.js?v=16';
import {uploadImage,assetURL} from './local-assets.js?v=16';
const $=id=>document.getElementById(id);
export function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
export function button(text,fn,cls){const b=el('button',text,cls);b.type='button';if(fn)b.addEventListener('click',fn);return b;}
export function badges(member){return [...(member.conditions||[]).map(id=>{const c=CONDITIONS.find(c=>c[0]===id);return c?[c[1],c[2]]:null;}).filter(Boolean),...(member.letters||[]).map(l=>[l,`Marker ${l}`])];}
export function badgeNodes(member){const container=el('span',undefined,'condition-badges');for(const[symbol,name]of badges(member)){const b=el('span',symbol,'condition-badge');b.title=name;b.setAttribute('aria-label',name);container.append(b);}return container;}
function imageFor(member){const img=el('img');img.alt='';img.width=img.height=40;img.draggable=false;setFace(img,member);return img;}
function input(value,label,change,type='text'){const field=el('input');field.type=type;field.value=value??'';field.setAttribute('aria-label',label);field.addEventListener('input',()=>change(field.value));return field;}
function labeled(label,field){const wrap=el('label',label,'field-label');wrap.append(field);return wrap;}
export function createCombatUI({map,player,getState,commit,announce}){
  const stage=$('map-stage'),overlay=el('div',undefined,player?'player-initiative':'initiative-preview');overlay.id='initiative-overlay';stage.append(overlay);
  const rows=new Map();let panel,list,left,signature='',overlayDrag=null;
  if(!player){
    left=el('section',undefined,'combat-roster');left.id='combat-roster';document.querySelector('.encounter-heading').after(left);
    panel=el('aside',undefined,'initiative-panel');panel.id='initiative-panel';panel.tabIndex=0;panel.setAttribute('aria-label','Initiative turn order. Use arrow keys or Space.');const heading=el('div',undefined,'initiative-heading');heading.append(el('h2','Initiative'),button('←',()=>commit(stepTurn(getState(),-1),'Previous turn.')),button('→',()=>commit(stepTurn(getState(),1),'Next turn.')));heading.children[1].setAttribute('aria-label','Previous turn');heading.children[2].setAttribute('aria-label','Next turn');list=el('div');list.id='initiative-list';
    const visibility=el('label',undefined,'check-label');const check=input('', 'Show player order',()=>{const s=getState();commit({...s,initiativeOverlay:{...s.initiativeOverlay,visible:check.checked}},'Player order visibility updated.');},'checkbox');check.id='initiative-visible';visibility.append(check,document.createTextNode('Player order'));panel.append(heading,visibility,el('p','Enter scores beside the portraits. Arrow keys or Space advance the turn.','tool-hint'),list);document.querySelector('.workspace').append(panel);
    document.addEventListener('keydown',e=>{if(e.defaultPrevented||document.querySelector('dialog[open],.token-status-editor')||e.target.closest('input,textarea,select,[contenteditable],[data-character],[data-shape],.party-token')||(e.key===' '&&e.target.closest('button')&&!panel.contains(e.target)))return;if(['ArrowRight','ArrowDown',' ','ArrowLeft','ArrowUp'].includes(e.key)&&initiativeOrder(getState()).length){e.preventDefault();commit(stepTurn(getState(),['ArrowLeft','ArrowUp'].includes(e.key)?-1:1),'Turn updated.');}});
    overlay.tabIndex=0;overlay.setAttribute('aria-label','Player initiative position. Drag to place.');
    overlay.addEventListener('pointerdown',e=>{if(e.button!==0)return;e.stopPropagation();e.preventDefault();overlayDrag={id:e.pointerId,x:e.clientX,y:e.clientY,start:{...getState().initiativeOverlay},rect:stage.getBoundingClientRect()};overlay.setPointerCapture(e.pointerId);});
    overlay.addEventListener('pointermove',e=>{if(!overlayDrag)return;const d=overlayDrag;overlay.style.left=`${Math.max(0,Math.min(.8,d.start.x+(e.clientX-d.x)/d.rect.width))*100}%`;overlay.style.top=`${Math.max(0,Math.min(.85,d.start.y+(e.clientY-d.y)/d.rect.height))*100}%`;});
    overlay.addEventListener('pointerup',()=>{if(!overlayDrag)return;overlayDrag=null;const s=getState();commit({...s,initiativeOverlay:{...s.initiativeOverlay,x:parseFloat(overlay.style.left)/100,y:parseFloat(overlay.style.top)/100}},'Player order moved.');});
    overlay.addEventListener('pointercancel',()=>{overlayDrag=null;render();});
    overlay.addEventListener('keydown',e=>{const delta={ArrowLeft:[-.01,0],ArrowRight:[.01,0],ArrowUp:[0,-.01],ArrowDown:[0,.01]}[e.key];if(!delta)return;e.preventDefault();e.stopPropagation();const s=getState(),p=s.initiativeOverlay;commit({...s,initiativeOverlay:{...p,x:Math.max(0,Math.min(.8,p.x+delta[0])),y:Math.max(0,Math.min(.85,p.y+delta[1]))}},'Player order moved.');});
  }
  async function showStat(member){if(!member.statCard){announce('Add a stat card image in Encounter.');return;}let d=$('stat-card-dialog');if(!d){d=el('dialog');d.id='stat-card-dialog';document.body.append(d);}d.replaceChildren(button('Close',()=>d.close()));const img=el('img');img.alt=`${member.name} stat card`;try{img.src=await assetURL(member.statCard);d.append(img);d.showModal();}catch(e){announce(e.message);}}
  function rosterSection(title,members,monster){const section=el('div',undefined,'static-roster');section.append(el('h3',title));if(!members.length)section.append(el('p',monster?'Choose an encounter above.':'Add players in Party.','tool-hint'));
    for(const m of members){const row=el('div',undefined,'combat-roster-row');row.dataset.member=m.id;const face=button('',()=>monster?showStat(combatants(getState()).find(p=>p.id===m.id)):document.dispatchEvent(new CustomEvent('edit-party-member',{detail:m.id})),'roster-portrait');face.setAttribute('aria-label',monster?`Open ${m.name} stat card`:`Edit ${m.name}`);face.append(imageFor(m),el('span',m.name));
      const score=input(m.initiative,`Initiative for ${m.name}`,v=>{const parsed=parseInitiative(v);if(/^-$|^-?\d+[.,]$/.test(v))return;if(v.trim()&&parsed===null){score.value=combatants(getState()).find(p=>p.id===m.id)?.initiative??'';announce('Enter a number, using a dot or comma for decimals.');return;}commit(patchMember(getState(),m.id,{initiative:parsed}),'Initiative updated.');});score.addEventListener('blur',()=>score.value=combatants(getState()).find(p=>p.id===m.id)?.initiative??'');score.inputMode='decimal';score.placeholder='—';score.className='initiative-input';
      row.append(face,score);if(monster){const visible=input('',`Show ${m.name} to players`,()=>commit(patchMember(getState(),m.id,{visible:visible.checked}),'Monster visibility updated.'),'checkbox');visible.checked=m.visible;visible.title='Visible to players';row.append(visible);}section.append(row);
    }return section;
  }
  function render(){const s=getState(),order=initiativeOrder(s),active=player?s.turnId:(order.some(m=>m.id===s.turnId)?s.turnId:order[0]?.id),players=initiativeOrder(s,true);
    if(!overlayDrag){overlay.style.left=`${s.initiativeOverlay.x*100}%`;overlay.style.top=`${s.initiativeOverlay.y*100}%`;}
    overlay.hidden=!s.initiativeOverlay.visible||!players.length;
    overlay.replaceChildren();if(!player)overlay.append(el('span','Player order · drag to place','overlay-kicker'));
    for(const m of players){const row=el('div',undefined,`public-turn${m.id===active?' current':''}`);row.append(badgeNodes(m),imageFor(m),el('span',m.name));overlay.append(row);}
    if(player)return;
    $('initiative-visible').checked=s.initiativeOverlay.visible;
    const sig=JSON.stringify([s.campaign?.activeParty,s.campaign?.activeEncounter,s.campaign?.parties.map(g=>[g.id,g.name]),s.campaign?.encounters.map(g=>[g.id,g.name]),s.roster.map(({initiative,position,hp,conditions,letters,...m})=>m),s.monsters.map(({initiative,position,hp,conditions,letters,...m})=>m)]);if(sig!==signature){signature=sig;const p=s.campaign?.parties.find(p=>p.id===s.campaign.activeParty),g=s.campaign?.encounters.find(g=>g.id===s.campaign.activeEncounter);left.replaceChildren(rosterSection(p?.name||'Party',s.roster,false),rosterSection(g?.name||'Encounter',s.monsters||[],true));}
    for(const row of left.querySelectorAll('[data-member]')){const m=combatants(s).find(m=>m.id===row.dataset.member),field=row.querySelector('.initiative-input');if(m&&field!==document.activeElement)field.value=m.initiative??'';}
    for(const[id,row]of rows)if(!order.some(m=>m.id===id)){row.remove();rows.delete(id);}
    let empty=list.querySelector('.initiative-empty');if(!order.length){if(!empty)list.append(el('p','No initiative scores yet.','initiative-empty tool-hint'));}else empty?.remove();
    for(const m of order){let row=rows.get(m.id);if(!row){row=el('div',undefined,'turn-row');row.dataset.turn=m.id;const select=button('',()=>commit({...getState(),turnId:m.id},'Turn selected.'),'turn-select');const b=el('span'),img=imageFor(m),name=el('span');select.append(b,img,name);row.append(select);if(m.monster){const hp=el('span',undefined,'hp-display'),box=el('div',undefined,'hp-adjust');const amount=input('',`Damage or healing for ${m.name}`,()=>{},'number');amount.min=0;amount.step=1;amount.placeholder='0';const adjust=heal=>{const member=getState().monsters.find(p=>p.id===m.id);commit(patchMember(getState(),m.id,changeHP(member,amount.value,heal)),`${m.name} HP updated.`);amount.value='';};const damage=button('⚔',()=>adjust(false)),heal=button('✚',()=>adjust(true));damage.setAttribute('aria-label',`Damage ${m.name}`);heal.setAttribute('aria-label',`Heal ${m.name}`);box.append(damage,amount,heal);row.append(hp,box);}rows.set(m.id,row);}
      row.classList.toggle('current',active===m.id);const select=row.firstElementChild;select.setAttribute('aria-label',`${m.name}, initiative ${m.initiative}`);select.children[0].replaceChildren(badgeNodes(m));setFace(select.children[1],m);select.children[2].textContent=m.name;if(m.monster)row.querySelector('.hp-display').textContent=`${m.hp} / ${m.maxHp} HP`;list.append(row);
    }
  }
  return {render};
}

export function createLibraries({map,getState,commit,announce}){
  for(const kind of ['party','encounter']){
    const monster=kind==='encounter',title=monster?'Encounter':'Party',key=monster?'encounters':'parties',active=monster?'activeEncounter':'activeParty';let selected=null,memberId=null;const error=el('p','','save-error');error.setAttribute('role','alert');
    const open=button(`${title} ⌄`,()=>show(),'map-picker');open.id=`open-${kind}-library`;open.setAttribute('aria-haspopup','dialog');document.querySelector('.site-identity').append(open);
    const dialog=el('dialog',undefined,'library-dialog');dialog.id=`${kind}-dialog`;const heading=el('div',undefined,'map-menu-heading');heading.append(el('h2',title),button('×',()=>dialog.close(),'quiet'));
    const layout=el('div',undefined,'library-layout'),groups=el('section',undefined,'library-groups'),members=el('section',undefined,'library-members');layout.append(groups,members);const footer=el('div',undefined,'dialog-actions');const apply=button(monster?'Use encounter':'Use party',()=>{commit(applyGroup(getState(),kind,selected),`${title} applied.`);render();},'primary');footer.append(button('Keep playing',()=>dialog.close()),apply);dialog.append(heading,error,layout,footer);document.body.append(dialog);
    function editGroup(fn,message='',redraw=true,groupId=selected){const s=syncCampaign(getState()),list=s.campaign[key].map(g=>g.id===groupId?fn(g):g),campaign={...s.campaign,[key]:list};let next={...s,campaign};if(campaign[active]===groupId)next={...next,[monster?'monsters':'roster']:list.find(g=>g.id===groupId)?.members||[]};commit(next,message);if(redraw)render();else{const updated=list.find(g=>g.id===selected);for(const b of groups.querySelectorAll('[data-group]')){const g=list.find(g=>g.id===b.dataset.group);if(g)b.textContent=`${g.name}${g.id===campaign[active]?' · Active':''}`;}for(const b of members.querySelectorAll('[data-member-id]')){const m=updated?.members.find(m=>m.id===b.dataset.memberId);if(m)b.lastElementChild.textContent=m.name;}}}
    function addGroup(){const id=crypto.randomUUID(),s=syncCampaign(getState());if(s.campaign[key].length>=20){announce('Up to 20 groups per library.');return;}selected=id;memberId=null;commit({...s,campaign:{...s.campaign,[key]:[...s.campaign[key],{id,name:title,members:[]}]}},`${title} created.`);render();}
    function render(){const s=syncCampaign(getState()),items=s.campaign[key];if(!items.some(g=>g.id===selected))selected=s.campaign[active]||items[0]?.id;const group=items.find(g=>g.id===selected);groups.replaceChildren(el('h3',monster?'Encounters':'Parties'),button(`+ New ${kind}`,addGroup));
      for(const g of items){const b=button(`${g.name}${g.id===s.campaign[active]?' · Active':''}`,()=>{selected=g.id;memberId=null;render();},'library-group');b.dataset.group=g.id;b.setAttribute('aria-pressed',g.id===selected);groups.append(b);}members.replaceChildren();apply.disabled=!group;if(!group){members.append(el('p','Create a group to add its members.','tool-hint'));return;}
      const name=input(group.name,`${title} name`,v=>editGroup(g=>({...g,name:v.trim().slice(0,48)||title}),'',false));name.maxLength=48;const actions=el('div',undefined,'library-member-actions');actions.append(labeled(`${title} name`,name),button(monster?'+ Add monster':'+ Add player',()=>{if(group.members.length>=60){announce('Up to 60 members per group.');return;}memberId=crypto.randomUUID();const point=formation(map,getState().party,60)[group.members.length]||getState().party;editGroup(g=>({...g,members:[...g.members,normalizeMember({id:memberId,name:monster?'Goblin':`Player ${g.members.length+1}`,portrait:monster?0:g.members.length%30,position:point,visible:false},0,monster)]}));}));members.append(actions);
      if(!group.members.some(m=>m.id===memberId))memberId=group.members[0]?.id;
      const strip=el('div',undefined,'library-member-strip');for(const m of group.members){const b=button('',()=>{memberId=m.id;render();},'library-member');b.dataset.memberId=m.id;b.setAttribute('aria-pressed',m.id===memberId);b.append(imageFor(m),el('span',m.name));strip.append(b);}members.append(strip);
      if(!group.members.some(m=>m.id===memberId))memberId=group.members[0]?.id;const m=group.members.find(m=>m.id===memberId);if(!m){members.append(el('p',`Add ${monster?'a monster':'a player'} to this group.`,'tool-hint'));return;}
      const patch=(p,redraw=true)=>editGroup(g=>({...g,members:g.members.map(v=>v.id===memberId?{...v,...p}:v)}),'',redraw);const fields=el('div',undefined,'member-fields');const naming=input(m.name,monster?'Monster name':'Player name',v=>patch({name:v.trim().slice(0,32)||'Unnamed'},false));naming.maxLength=32;fields.append(labeled('Name',naming));
      if(monster){const size=input(m.size,'Token size in feet',v=>patch({size:fiveFeet(v)},false),'number');size.min=5;size.max=200;size.step=5;size.addEventListener('blur',()=>size.value=fiveFeet(size.value));const maximum=input(m.maxHp,'Maximum HP',v=>{const maxHp=Math.max(0,Math.min(100000,Math.round(Number(v)||0)));patch({maxHp,hp:Math.min(syncCampaign(getState()).campaign[key].find(g=>g.id===selected).members.find(v=>v.id===memberId).hp,maxHp)},false);},'number'),current=input(m.hp,'Current HP',v=>patch({hp:Math.max(0,Math.min(syncCampaign(getState()).campaign[key].find(g=>g.id===selected).members.find(v=>v.id===memberId).maxHp,Math.round(Number(v)||0)))},false),'number');maximum.min=current.min=0;maximum.step=current.step=1;fields.append(labeled('Size · ft',size),labeled('Max HP',maximum),labeled('Current HP',current));}
      members.append(fields);const choices=el('div',undefined,'avatar-options');const choose=button('Premade portraits',()=>{grid.hidden=false;choose.setAttribute('aria-pressed','true');});choose.setAttribute('aria-pressed',!m.avatar);const upload=el('input');upload.type='file';upload.accept='image/png,image/jpeg,image/webp';upload.hidden=true;upload.setAttribute('aria-label',`Upload ${monster?'monster':'player'} portrait`);const uploadButton=button('Upload image',()=>upload.click());uploadButton.setAttribute('aria-pressed',!!m.avatar);upload.addEventListener('input',async()=>{const groupId=selected,id=memberId;try{const a=await uploadImage(upload.files[0]);editGroup(g=>({...g,members:g.members.map(v=>v.id===id?{...v,avatar:a.id}:v)}),'',true,groupId);}catch(e){error.textContent=e.message;}});choices.append(choose,uploadButton,upload,button('Remove member',()=>{editGroup(g=>({...g,members:g.members.filter(v=>v.id!==memberId)}));},'quiet'));members.append(choices);
      const grid=el('div',undefined,'portrait-options library-portraits');grid.hidden=!!m.avatar;(monster?MONSTERS:PORTRAITS).forEach((name,index)=>{const b=button('',()=>patch({portrait:index,avatar:null,...(monster&&MONSTERS.includes(syncCampaign(getState()).campaign[key].find(g=>g.id===selected).members.find(v=>v.id===memberId).name)?{name}: {})}),'portrait-option');b.setAttribute('aria-label',name);b.title=name;b.setAttribute('aria-pressed',m.portrait===index&&!m.avatar);const face=el('span',undefined,'portrait-thumb');portraitStyle(face,index,monster);b.append(face);grid.append(b);});members.append(grid);
      if(monster){const stat=el('input');stat.type='file';stat.accept='image/png,image/jpeg,image/webp';stat.setAttribute('aria-label','Upload monster stat card');stat.addEventListener('input',async()=>{const groupId=selected,id=memberId;try{const a=await uploadImage(stat.files[0],'stat');editGroup(g=>({...g,members:g.members.map(v=>v.id===id?{...v,statCard:a.id}:v)}),'',true,groupId);}catch(e){error.textContent=e.message;}});members.append(labeled(m.statCard?'Stat card attached · replace image':'Stat card image',stat));}
    }
    function show(){error.textContent='';selected=getState().campaign?.[active];render();dialog.showModal();}
    if(!monster)document.addEventListener('edit-party-member',e=>{memberId=e.detail;show();});
  }
}
