import {uploadImage,assetURL} from './local-assets.js?v=27';
import {el,button} from './combat-ui.js?v=27';
import {assetId,safeId} from './combat-state.js?v=27';
export function customCatalog(sessionKey){try{const entries=JSON.parse(localStorage.getItem(`${sessionKey}:custom-maps`))||[];return entries.filter(validCustomEntry);}catch{return [];}}
export function validCustomEntry(e){const m=e?.map;return !!(e&&safeId(e.id)&&e.id.startsWith('custom-')&&m&&m.id===e.id&&m.schemaVersion===1&&m.version==='1'&&e.thumbnail===m.art?.base&&e.title===m.title&&Object.keys(m.art||{}).every(k=>['base','roofs'].includes(k))&&m.lighting===undefined&&m.userMap===true&&typeof m.title==='string'&&m.title.length<=80&&m.width>=100&&m.width<=4096&&m.height>=100&&m.height<=4096&&Number.isFinite(m.grid?.size)&&m.grid.size>=1&&m.grid.distance===5&&assetId(m.art?.base)&&m.art.base===m.art.roofs&&Array.isArray(m.places)&&m.places.length===0&&Array.isArray(m.interactions)&&m.interactions.length===0);}
export function saveCustomCatalog(sessionKey,entries){if(!entries.every(validCustomEntry)||entries.length>40)throw new Error('Invalid custom map library.');localStorage.setItem(`${sessionKey}:custom-maps`,JSON.stringify(entries));}
export function createMapUpload({sessionKey,catalog,onAdded,announce}){
  const menu=document.getElementById('map-dialog'),bar=el('div',undefined,'map-source-tabs');bar.append(el('span','Ull Hexa maps & your images'),button('+ Upload map image',()=>{upload.value='';upload.click();}));menu.querySelector('.map-menu-heading').after(bar);
  const upload=el('input');upload.type='file';upload.accept='image/png,image/jpeg,image/webp';upload.hidden=true;upload.setAttribute('aria-label','Upload battle map');bar.append(upload);
  const dialog=el('dialog',undefined,'map-upload-dialog');dialog.id='map-upload-dialog';document.body.append(dialog);
  const error=el('p','','save-error');error.setAttribute('role','alert');bar.after(error);
  upload.addEventListener('input',async()=>{if(!upload.files[0])return;error.textContent='Preparing your image…';try{const a=await uploadImage(upload.files[0],'map'),image=new Image();image.src=a.data;await image.decode();let squares=32,calibration=[],distance=5;dialog.replaceChildren(el('h2','Fit your map to the grid'),el('p','Use the entire image. Adjust the grid width, or click two known points and enter their distance. Each grid square is 5 ft.','tool-hint'));
    const name=el('input');name.value=upload.files[0].name.replace(/\.[^.]+$/,'').slice(0,80);name.maxLength=80;name.setAttribute('aria-label','Map title');
    const width=el('input');width.type='number';width.min=2;width.max=150;width.step=.1;width.value=squares;width.setAttribute('aria-label','Squares across image');
    const known=el('input');known.type='number';known.min=5;known.max=1000;known.step=5;known.value=5;known.setAttribute('aria-label','Calibration distance in feet');
    const output=el('output'),canvas=el('canvas');canvas.width=900;canvas.height=Math.round(900*a.height/a.width);canvas.className='map-calibration';const c=canvas.getContext('2d');
    function draw(){c.drawImage(image,0,0,canvas.width,canvas.height);const step=canvas.width/squares;c.strokeStyle='#ffffffaa';c.lineWidth=1;for(let x=0;x<canvas.width;x+=step){c.beginPath();c.moveTo(x,0);c.lineTo(x,canvas.height);c.stroke();}for(let y=0;y<canvas.height;y+=step){c.beginPath();c.moveTo(0,y);c.lineTo(canvas.width,y);c.stroke();}c.fillStyle='#e8ba71';for(const p of calibration){c.beginPath();c.arc(p[0]*canvas.width,p[1]*canvas.height,5,0,Math.PI*2);c.fill();}output.textContent=`${(squares*5).toFixed(1)} × ${(squares*5*a.height/a.width).toFixed(1)} ft`;}
    function calibrate(){if(calibration.length===2){const[p,q]=calibration,px=Math.hypot((p[0]-q[0])*a.width,(p[1]-q[1])*a.height);if(px>2){squares=Math.max(2,Math.min(150,a.width/(px/distance*5)));width.value=Number(squares.toFixed(3));}}draw();}
    canvas.addEventListener('click',e=>{const r=canvas.getBoundingClientRect(),scale=Math.min(r.width/canvas.width,r.height/canvas.height),w=canvas.width*scale,h=canvas.height*scale,p=[(e.clientX-r.left-(r.width-w)/2)/w,(e.clientY-r.top-(r.height-h)/2)/h];if(p.some(n=>n<0||n>1))return;if(calibration.length===2)calibration=[];calibration.push(p);calibrate();});width.addEventListener('input',()=>{squares=Math.max(2,Math.min(150,Number(width.value)||32));calibration=[];draw();});known.addEventListener('input',()=>{distance=Math.max(5,Math.min(1000,Number(known.value)||5));calibrate();});
    const controls=el('div',undefined,'calibration-controls');for(const[t,f]of [['Title',name],['Squares across',width],['Known distance · ft',known]]){const label=el('label',t,'field-label');label.append(f);controls.append(label);}controls.append(output);dialog.append(controls,canvas);
    const actions=el('div',undefined,'dialog-actions');actions.append(button('Cancel',()=>dialog.close()),button('Add map',async()=>{try{const id=`custom-${crypto.randomUUID()}`,title=name.value.trim()||'Custom map',map={schemaVersion:1,userMap:true,id,version:'1',title,width:a.width,height:a.height,grid:{size:a.width/squares,distance:5,unit:'ft',color:'#ffffff'},art:{base:a.id,roofs:a.id},partyStart:[.5,.5],places:[],interactions:[]};const entry={id,title,identity:title,edition:'CUSTOM MAP',category:'Your maps',subtitle:'Uploaded image',thumbnail:a.id,map};const entries=[...customCatalog(sessionKey),entry];saveCustomCatalog(sessionKey,entries);catalog.push(entry);onAdded(entry);dialog.close();announce('Map added. Select it in Maps to apply.');}catch(e){announce(e.message);}},'primary'));dialog.append(actions);error.textContent='';dialog.showModal();draw();
  }catch(e){error.textContent=e.message;}});
}
export async function resolveMapArt(map){const entries=await Promise.all(Object.entries(map.art).map(async([key,value])=>[key,assetId(value)?await assetURL(value):value]));return Object.fromEntries(entries);}
