import {setFace} from './token-portraits.js?v=18';
import {SHAPE_COLORS,clamp,feetToWorld,setTokenMode,newShape,resizeShape,rotateShape} from './encounter-state.js?v=18';
import {CONDITIONS,combatants,patchMember,snapPoint} from './combat-state.js?v=18';
import {el,button,badgeNodes} from './combat-ui.js?v=18';
const NS='http://www.w3.org/2000/svg',$=id=>document.getElementById(id);
const node=(tag,attrs={},text)=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e;};
const names=['Blue','Brown','Red','Orange','Black','White','Green'];
export function createEncounterTools({map,player,getState,commit,preview,finishDrag,pointAt,announce,getTool,livePositions}){
  const svg=$('map'),stage=$('map-stage'),tokens=el('div');tokens.id='character-tokens';stage.append(tokens);
  const overlay=node('svg',{id:'shape-handle-overlay','aria-label':'Spell area handles'});if(!player){overlay.append($('shape-handles'));stage.append(overlay);}
  let geometry,selected=null,drag=null,frame=0,pending=null,status=null,lastLive=0;const tokenNodes=new Map();
  const world=p=>[p[0]*map.width,p[1]*map.height];
  function position(){if(!geometry)return;const{matrix,left,top}=geometry;for(const m of combatants(getState())){const t=tokenNodes.get(m.id);if(!t)continue;const[x,y]=world(m.position),size=feetToWorld(map,m.size||5)/50*Math.hypot(matrix.a,matrix.b);t.style.transform=`translate3d(${matrix.a*x+matrix.c*y+matrix.e-left-25*size}px,${matrix.b*x+matrix.d*y+matrix.f-top-25*size}px,0) scale(${size})`;}}
  function updateGeometry(){const matrix=svg.getScreenCTM(),r=stage.getBoundingClientRect();if(matrix)geometry={matrix,left:r.left+stage.clientLeft,top:r.top+stage.clientTop};position();positionStatus();}
  new ResizeObserver(updateGeometry).observe(stage);
  function renderCharacters(){const s=getState(),members=combatants(s);for(const[id,t]of tokenNodes)if(!members.some(m=>m.id===id)){t.remove();tokenNodes.delete(id);}for(const m of members){let t=tokenNodes.get(m.id);if(!t){t=el(player?'div':'button',undefined,'character-token');t.dataset.character=m.id;const img=el('img',undefined,'token-face');img.alt='';img.width=img.height=96;img.draggable=false;t.append(img,el('span',undefined,'token-label'),el('span',undefined,'token-badges'));if(!player){t.type='button';}tokenNodes.set(m.id,t);tokens.append(t);}t.hidden=m.monster?(player&&!m.visible):s.tokenMode!=='players';t.classList.toggle('concealed-token',m.monster===true&&m.visible!==true);t.classList.toggle('token-selected',status?.id===m.id);setFace(t.firstElementChild,m);t.children[1].textContent=m.name;const draft=status?.id===m.id?status.draft:m;t.children[2].replaceChildren(badgeNodes(draft));if(!player)t.setAttribute('aria-label',`${m.name}. Drag to move; double-click for conditions.`);}updateGeometry();}
  function footprint(s,thumb=false){const size=thumb?s.size:feetToWorld(map,s.size),attrs={fill:s.color,'fill-opacity':.28,stroke:s.color,'stroke-width':2,'vector-effect':'non-scaling-stroke'};if(s.type==='circle')return node('circle',{...attrs,r:size});if(s.type==='square')return node('rect',{...attrs,x:-size/2,y:-size/2,width:size,height:size});return node('path',{...attrs,d:`M0 0 L${-size*.5} ${-size*Math.sqrt(3)/2} A${size} ${size} 0 0 1 ${size*.5} ${-size*Math.sqrt(3)/2} Z`});}
  function renderShapes(){const s=getState();$('shape-layer').replaceChildren();for(const shape of s.shapes){if(player&&!shape.visible)continue;const[x,y]=world(shape.center),g=node('g',{class:'spell-shape','data-shape':shape.id,transform:`translate(${x} ${y}) rotate(${shape.rotation})`,...(player?{'pointer-events':'none'}:{tabindex:0,role:'button','aria-label':`${shape.type} ${shape.size} feet`})});const f=footprint(shape);if(!shape.visible)f.setAttribute('stroke-dasharray','7 5');g.append(f);$('shape-layer').append(g);}
    if(player)return;const shape=s.shapes.find(v=>v.id===selected);if(!shape)selected=null;$('shape-list').replaceChildren();$('shape-empty').hidden=!!s.shapes.length;
    for(const v of s.shapes){const b=button('',()=>{selected=v.id;$('spell-areas').open=true;renderShapes();},'shape-choice');b.setAttribute('aria-pressed',v.id===selected);b.setAttribute('aria-label',`${v.type}, ${v.size} feet, ${v.visible?'visible':'hidden'}`);const icon=node('svg',{viewBox:'-25 -25 50 50',width:42,height:42});const g=node('g',{transform:`translate(0 ${v.type==='cone'?10:0}) rotate(${v.rotation}) scale(${v.type==='circle'?18/v.size:28/v.size})`});g.append(footprint(v,true));icon.append(g);b.append(icon,el('span',v.visible?'●':'○','visibility-dot'));$('shape-list').append(b);}
    $('shape-editor').hidden=!shape;if(shape){$('shape-visible').textContent=shape.visible?'Hide from players':'Show to players';$('shape-visible').setAttribute('aria-pressed',shape.visible);$('shape-visibility-label').textContent=shape.visible?'Visible to players':'DM only';[...$('shape-colors').children].forEach(b=>b.setAttribute('aria-pressed',b.dataset.color===shape.color));}renderHandles(shape);
  }
  function renderHandles(s){overlay.setAttribute('viewBox',svg.getAttribute('viewBox'));overlay.style.display=s?'':'none';const layer=$('shape-handles');layer.replaceChildren();if(!s)return;const[x,y]=world(s.center),r=feetToWorld(map,s.size),unit=1/getState().camera.zoom,g=node('g',{'data-shape':s.id,transform:`translate(${x} ${y}) rotate(${s.rotation})`});let handles;
    if(s.type==='circle')handles=[['size',0,-r],['size',r,0],['size',0,r],['size',-r,0]];
    else if(s.type==='square')handles=[['size',-r/2,-r/2],['size',r/2,-r/2],['size',r/2,r/2],['size',-r/2,r/2],['rotate',0,-r/2,0],['rotate',r/2,0,90],['rotate',0,r/2,180],['rotate',-r/2,0,270]];
    else handles=[['rotate',0,0,180],['rotate',0,-r,0],['size',-.5*r,-Math.sqrt(3)/2*r],['size',.5*r,-Math.sqrt(3)/2*r]];
    handles.forEach(([type,hx,hy,angle=0],i)=>{const h=node('g',{'data-handle':type,'data-angle':angle,tabindex:0,role:'button','aria-label':`${type==='rotate'?'Rotate':'Resize'} ${s.type} handle ${i+1}`,'pointer-events':'all',class:'shape-handle'});h.append(node('circle',{cx:hx,cy:hy,r:16*unit,fill:'transparent'}));h.append(type==='rotate'?node('circle',{cx:hx,cy:hy,r:7*unit,fill:'#e8ba71',stroke:'#17251d','stroke-width':2*unit}):node('rect',{x:hx-7*unit,y:hy-7*unit,width:14*unit,height:14*unit,rx:2*unit,fill:'#fff3ce',stroke:'#17251d','stroke-width':2*unit}));g.append(h);});layer.append(g,node('text',{class:'marker-label',x,y:y-r-24*unit,'text-anchor':'middle','font-size':16*unit,'pointer-events':'none'},`${s.size} ft ${s.type==='circle'?'radius':s.type==='square'?'side':'cone'}`));}
  const updateShape=patch=>commit({...getState(),shapes:getState().shapes.map(s=>s.id===selected?{...s,...patch}:s)},'Area updated.');
  function closeStatus(){if(!status)return;const{id,draft,root}=status;status=null;root.remove();commit(patchMember(getState(),id,{conditions:draft.conditions,letters:draft.letters}),'Conditions applied.');}
  function positionStatus(){if(!status)return;const token=tokenNodes.get(status.id);if(!token)return;const r=token.getBoundingClientRect(),s=stage.getBoundingClientRect(),root=status.root;root.style.setProperty('--status-max-height',`${stage.clientHeight-8}px`);root.style.left=`${clamp(r.left-s.left+r.width/2-120,4,Math.max(4,s.width-root.offsetWidth-4))}px`;root.style.top=`${clamp(r.top-s.top-50,4,Math.max(4,s.height-root.offsetHeight-4))}px`;}
  function openStatus(id){closeStatus();const member=combatants(getState()).find(m=>m.id===id);if(!member)return;const root=el('div',undefined,'token-status-editor'),letters=el('div',undefined,'letter-options'),conditions=el('div',undefined,'condition-options');root.setAttribute('role','dialog');root.setAttribute('aria-label',`${member.name} conditions`);root.append(letters,el('div',undefined,'status-spacer'),conditions);status={id,draft:structuredClone(member),root};stage.append(root);
    const toggle=(field,value,b)=>{const list=status.draft[field];status.draft[field]=list.includes(value)?list.filter(v=>v!==value):[...list,value];b.setAttribute('aria-pressed',status.draft[field].includes(value));renderCharacters();};
    for(const l of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'){const b=button(l,()=>toggle('letters',l,b));b.setAttribute('aria-pressed',member.letters.includes(l));letters.append(b);}for(const[id,symbol,name]of CONDITIONS){const b=button(`${symbol}  ${name}`,()=>toggle('conditions',id,b));b.setAttribute('aria-pressed',member.conditions.includes(id));conditions.append(b);}conditions.append(button('Apply & close',closeStatus,'primary'));renderCharacters();positionStatus();}
  function flush(){cancelAnimationFrame(frame);frame=0;if(pending){const p=pending;pending=null;preview(p.state,p.characters);if(p.characters&&performance.now()-lastLive>32){lastLive=performance.now();livePositions?.();}}}
  function queue(state,characters){pending={state,characters};if(!frame)frame=requestAnimationFrame(flush);}
  if(!player){
    stage.addEventListener('dblclick',e=>{if(getTool()||e.target.closest('.token-status-editor'))return;const token=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-character]');if(token){e.preventDefault();e.stopPropagation();openStatus(token.dataset.character);}});
    ['party','players'].forEach(mode=>$(`mode-${mode}`).addEventListener('click',()=>commit(setTokenMode(map,getState(),mode),'Token display updated.')));
    document.querySelectorAll('[data-add-shape]').forEach(b=>b.addEventListener('click',()=>{if(getState().shapes.length>=32)return;const s=getState(),shape=newShape(b.dataset.addShape,[s.camera.x,s.camera.y],crypto.randomUUID());selected=shape.id;$('spell-areas').open=true;commit({...s,shapes:[...s.shapes,shape]},'Area added, hidden from players.');}));
    SHAPE_COLORS.forEach((color,i)=>{const b=button('',()=>updateShape({color}),'color-swatch');b.dataset.color=color;b.style.backgroundColor=color;b.setAttribute('aria-label',`${names[i]} area`);$('shape-colors').append(b);});
    $('shape-visible').addEventListener('click',()=>{const s=getState().shapes.find(s=>s.id===selected);if(s)updateShape({visible:!s.visible});});$('delete-shape').addEventListener('click',()=>commit({...getState(),shapes:getState().shapes.filter(s=>s.id!==selected)},'Area removed.'));
    document.addEventListener('pointerdown',e=>{if(status&&!status.root.contains(e.target)&&!e.target.closest(`[data-character="${status.id}"]`))closeStatus();},true);
    document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeStatus();selected=null;renderShapes();}});
    stage.addEventListener('pointerdown',e=>{if(e.button!==0||getTool()||e.target.closest('.token-status-editor,#initiative-overlay'))return;const character=e.target.closest('[data-character]'),shape=e.target.closest('[data-shape]'),handle=e.target.closest('[data-handle]');if(!character&&!shape){if(selected){selected=null;renderShapes();}return;}e.stopImmediatePropagation();e.preventDefault();if(shape){selected=shape.dataset.shape;$('spell-areas').open=true;}const point=pointAt(e),start=structuredClone(getState());drag={id:e.pointerId,character:character?.dataset.character,shape:shape?.dataset.shape,handle:handle?.dataset.handle,angle:Number(handle?.dataset.angle)||0,start,point,x:e.clientX,y:e.clientY,moved:false};stage.setPointerCapture(e.pointerId);if(character)character.classList.add('is-dragging');else renderShapes();},true);
    stage.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;e.stopImmediatePropagation();if(!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<1)return;drag.moved=true;const p=pointAt(e);if(!p)return;const state=getState();if(drag.character){const m=combatants(drag.start).find(m=>m.id===drag.character);let position=m.position.map((n,i)=>clamp(n+p[i]-drag.point[i],0,1));if(state.snap)position=snapPoint(map,position,m.size);queue(patchMember(state,m.id,{position}),true);}else{const original=drag.start.shapes.find(s=>s.id===drag.shape);let next;if(drag.handle==='rotate'){if(original.type==='cone'&&drag.angle===180){const r=feetToWorld(map,original.size),a=original.rotation*Math.PI/180;const pivot=[original.center[0]+Math.sin(a)*r/map.width,original.center[1]-Math.cos(a)*r/map.height];const angle=Math.atan2((p[1]-pivot[1])*map.height,(p[0]-pivot[0])*map.width)*180/Math.PI-90;next={...original,rotation:(angle+720)%360};}else next=rotateShape(map,original,p,drag.angle);}else if(drag.handle)next=resizeShape(map,original,p);else next={...original,center:original.center.map((n,i)=>clamp(n+p[i]-drag.point[i],0,1))};queue({...state,shapes:state.shapes.map(s=>s.id===next.id?next:s)},false);}},true);
    stage.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;e.stopImmediatePropagation();flush();const d=drag;drag=null;tokenNodes.get(d.character)?.classList.remove('is-dragging');if(d.moved)finishDrag(d.start,d.character?'Token moved.':'Area adjusted.');else render();},true);
    stage.addEventListener('pointercancel',e=>{if(!drag||drag.id!==e.pointerId)return;e.stopImmediatePropagation();const d=drag;drag=null;pending=null;cancelAnimationFrame(frame);frame=0;tokenNodes.get(d.character)?.classList.remove('is-dragging');preview(d.start);livePositions?.();},true);
    stage.addEventListener('keydown',e=>{if(e.target.closest('.token-status-editor'))return;const target=e.target.closest('[data-character]'),shape=e.target.closest('[data-shape]'),offset={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(!target&&!shape)return;if(!offset)return;e.preventDefault();e.stopPropagation();if(target){const s=getState(),m=combatants(s).find(m=>m.id===target.dataset.character);let p=m.position.map((n,i)=>clamp(n+offset[i]*map.grid.size/(i?map.height:map.width),0,1));if(s.snap)p=snapPoint(map,p,m.size);commit(patchMember(s,m.id,{position:p}),'Token moved one square.');}else{selected=shape.dataset.shape;const s=getState().shapes.find(s=>s.id===selected),handle=e.target.closest('[data-handle]');if(handle){const delta=offset[0]||-offset[1];if(handle.dataset.handle==='rotate')updateShape({rotation:(s.rotation+delta*5+360)%360});else{const size=clamp(s.size+delta*5,5,200);updateShape({size,width:s.type==='circle'?size*2:size,height:s.type==='circle'?size*2:size});}}else updateShape({center:s.center.map((n,i)=>clamp(n+offset[i]*map.grid.size/(i?map.height:map.width),0,1))});}});
  }
  function render(){renderCharacters();renderShapes();if(!player){$('mode-party').setAttribute('aria-pressed',getState().tokenMode==='party');$('mode-players').setAttribute('aria-pressed',getState().tokenMode==='players');}}
  return {render,renderCharacterPositions:position,isDragging:()=>!!drag,clearSelection:()=>{selected=null;if(status){status.root.remove();status=null;}},closeStatus};
}
