import {featureEnabled} from './board-state.js?v=61';
import {createAuras} from './auras.js?v=61';
import {visibilityIcon,chevronIcon} from './control-icons.js?v=61';
import {consumeMapDismissal} from './map-dismissal.js?v=61';
import {itemFloorAt,itemOnSelectedFloor} from './floors.js?v=61';
import {elevation,tokenName,statusCursor} from './token-options.js?v=61';
import {shapeBounds,placeShapeLabel} from './shape-label.js?v=61';
import {conditionIcon} from './condition-icons.js?v=61';
import {shortcutAction,isTextEntry} from './keyboard.js?v=61';
import {setFace} from './token-portraits.js?v=61';
import {SHAPE_COLORS,clamp,feetToWorld,setTokenMode,newShape,resizeShape,rotateShape} from './encounter-state.js?v=61';
import {CONDITIONS,mapTokens as combatants,patchToken as patchMember,snapPoint,initiativeOrder,bringTokenToFront as bringToFront} from './combat-state.js?v=61';
import {el,button,badgeNodes} from './combat-ui.js?v=61';
const NS='http://www.w3.org/2000/svg',$=id=>document.getElementById(id);
const node=(tag,attrs={},text)=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e;};
const names=['Blue','Brown','Red','Orange','Black','White','Green','Purple'];
export function createEncounterTools({map,player,getState,commit,preview,finishDrag,pointAt,announce,getTool,setTool,livePositions}){
  const svg=$('map'),stage=$('map-stage'),tokens=el('div'),partyName=el('span','Party','map-party-label');tokens.id='character-tokens';tokens.append(partyName);stage.append(tokens);
  const borderWorld=3*feetToWorld(map,5)/50;svg.querySelector('.party-token>circle').setAttribute('stroke-width',borderWorld);
  const overlay=node('svg',{id:'shape-handle-overlay','aria-label':'Spell area handles'});if(!player){overlay.append($('shape-handles'));stage.append(overlay);}
  const sizeLabel=el('span',undefined,'shape-size-label');sizeLabel.hidden=true;if(!player)stage.append(sizeLabel);
  let itemSelected=null,itemComment=null,itemEditing=null;
  const itemDelete=button('×',()=>deleteSelectedItem(),'item-delete');itemDelete.setAttribute('aria-label','Delete selected item');itemDelete.hidden=true;const itemNotes=button('',()=>openItemComment(itemSelected),'item-notes');itemNotes.setAttribute('aria-label','Edit item notes');itemNotes.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="1"/><path d="M7 9h10M7 15h10"/></svg>';itemNotes.hidden=true;if(!player)stage.append(itemDelete,itemNotes);
  let located=null;
  let geometry,tokenBasis,panX=0,panY=0,selected=null,drag=null,frame=0,pending=null,status=null,palette=null,lastLive=0;const tokenNodes=new Map(),shapeNodes=new Map(),shapeChoices=new Map();
  const world=p=>[p[0]*map.width,p[1]*map.height];
  const auras=createAuras({map,player,getState,getDraft:m=>status?.id===m.id?status.draft:m,getTool,preview,finishDrag,prepare:()=>{selected=null;renderShapes();}});
  // Portrait dimensions follow world scale; labels stay in screen pixels and all rings match a five-foot player.
  function positionParty(){if(!geometry)return;const s=getState(),{matrix,left,top}=tokenBasis||geometry,[x,y]=world(s.party),scale=Math.hypot(matrix.a,matrix.b);partyName.hidden=s.tokenMode!=='party'||!featureEnabled(s,'party');partyName.style.transform=`translate3d(${matrix.a*x+matrix.c*y+matrix.e-left}px,${matrix.b*x+matrix.d*y+matrix.f-top+(21+borderWorld/2)*scale+6}px,0) translateX(-50%)`;}
  function position(id=null){if(!geometry)return;const{matrix,left,top}=tokenBasis||geometry,scale=Math.hypot(matrix.a,matrix.b),ringWidth=borderWorld*scale;if(!id)positionParty();for(const m of combatants(getState())){if(id&&m.id!==id)continue;const t=tokenNodes.get(m.id);if(!t)continue;if(t.style.zIndex!==String(m.stack||0))t.style.zIndex=String(m.stack||0);const[x,y]=world(m.position),diameter=feetToWorld(map,m.size||5)*scale,signature=`${diameter}:${ringWidth}`;if(t.dataset.geometry!==signature){t.dataset.geometry=signature;t.style.width=t.style.height=`${diameter}px`;t.style.setProperty('--token-scale',String(diameter/50));t.style.setProperty('--token-ring-width',`${ringWidth}px`);const ring=t.querySelector('.token-ring').firstElementChild;if(m.item){ring.setAttribute('x',ringWidth/2);ring.setAttribute('y',ringWidth/2);ring.setAttribute('width',Math.max(0,diameter-ringWidth));ring.setAttribute('height',Math.max(0,diameter-ringWidth));}else{ring.setAttribute('cx',diameter/2);ring.setAttribute('cy',diameter/2);ring.setAttribute('r',Math.max(0,(diameter-ringWidth)/2));}}const transform=`translate3d(${matrix.a*x+matrix.c*y+matrix.e-left-diameter/2}px,${matrix.b*x+matrix.d*y+matrix.f-top-diameter/2}px,0)`;if(t._position!==transform){t._position=transform;t.style.transform=transform;}}positionItemControls();auras.render();}
  function updateGeometry(view){
    let next;if(view?.scale){next={matrix:{a:view.scale,b:0,c:0,d:view.scale,e:view.x,f:view.y},left:0,top:0};}
    else {const matrix=svg.getScreenCTM(),r=stage.getBoundingClientRect();if(matrix)next={matrix,left:r.left+stage.clientLeft,top:r.top+stage.clientTop};}
    if(!next)return;geometry=next;
    if(!tokenBasis||Math.abs(tokenBasis.matrix.a-next.matrix.a)>1e-8){tokenBasis=next;panX=panY=0;tokens.style.transform='translate3d(0,0,0)';position();}
    else {const x=next.matrix.e-next.left-(tokenBasis.matrix.e-tokenBasis.left),y=next.matrix.f-next.top-(tokenBasis.matrix.f-tokenBasis.top);if(x!==panX||y!==panY){panX=x;panY=y;tokens.style.transform=`translate3d(${x}px,${y}px,0)`;}positionItemControls();}
    positionStatus();positionPalette();positionSizeLabel();auras.position();
  }
  new ResizeObserver(updateGeometry).observe(stage);
  function renderCharacters(){const s=getState(),members=combatants(s);for(const[id,t]of tokenNodes)if(!members.some(m=>m.id===id)){t.remove();tokenNodes.delete(id);}for(const m of members){let t=tokenNodes.get(m.id);if(!t){t=el(player?'div':'button',undefined,'character-token');t.dataset.character=m.id;const img=el('img',undefined,'token-face');img.alt='';img.width=img.height=96;img.draggable=false;const ring=node('svg',{class:'token-ring','aria-hidden':'true'});ring.append(node(m.item?'rect':'circle',{fill:'none'}));t.append(img,el('span',undefined,'token-label'),el('span',undefined,'token-badges'),ring);if(!player)t.type='button';tokenNodes.set(m.id,t);tokens.append(t);}t.style.zIndex=String(m.stack||0);const active=s.public?s.turnId:(initiativeOrder(s).some(v=>v.id===s.turnId)?s.turnId:initiativeOrder(s)[0]?.id);t.classList.toggle('token-located',!player&&located===m.id);t.classList.toggle('current-turn',!m.item&&active===m.id);t.classList.toggle('monster-token',m.monster===true);t.classList.toggle('item-token',m.item===true);t.hidden=m.monster||m.item?(player&&!m.visible):s.tokenMode!=='players';t.classList.toggle('concealed-token',(m.monster===true||m.item===true)&&(m.visible!==true||(m.item===true&&!itemOnSelectedFloor(m,s))));t.classList.toggle('token-selected',status?.id===m.id);t.classList.toggle('token-editing',m.item===true&&itemEditing===m.id);setFace(t.firstElementChild,m);const draft=status?.id===m.id?status.draft:m;t.classList.toggle('has-aura',!!draft.aura);t.children[1].textContent=tokenName(draft);t.children[2].replaceChildren(badgeNodes(draft));if(!player)t.setAttribute('aria-label',`${m.name}. Drag to move; double-click ${m.item?'to edit item':'for conditions'}.`);}updateVisibilityControls();updateGeometry();position();}
  function footprint(s,thumb=false){const size=thumb?s.size:feetToWorld(map,s.size),attrs={fill:s.color,'fill-opacity':.28,stroke:s.color,'stroke-width':2,'vector-effect':'non-scaling-stroke'};if(s.type==='circle')return node('circle',{...attrs,r:size});if(s.type==='square')return node('rect',{...attrs,x:-size/2,y:-size/2,width:size,height:size});return node('path',{...attrs,d:`M0 0 L${-size*.5} ${-size*Math.sqrt(3)/2} A${size} ${size} 0 0 1 ${size*.5} ${-size*Math.sqrt(3)/2} Z`});}
  function selectShape(id){itemSelected=null;closeItemComment();selected=id;renderShapes();renderCharacters();}
  function renderShapes(){const s=getState();for(const[id,g]of shapeNodes)if(!s.shapes.some(v=>v.id===id)){g.remove();shapeNodes.delete(id);}for(const[id,b]of shapeChoices)if(!s.shapes.some(v=>v.id===id)){b.remove();shapeChoices.delete(id);}
    for(const shape of s.shapes){let g=shapeNodes.get(shape.id);if(!g){g=node('g',{class:'spell-shape','data-shape':shape.id,...(player?{'pointer-events':'none'}:{tabindex:0,role:'button'})});g.append(footprint(shape));shapeNodes.set(shape.id,g);$('shape-layer').append(g);}const[x,y]=world(shape.center);g.setAttribute('transform',`translate(${x} ${y}) rotate(${shape.rotation})`);g.style.display=player&&shape.visible===false?'none':'';g.setAttribute('aria-label',`${shape.type} ${shape.size} feet`);const fresh=footprint(shape);for(const a of fresh.attributes)g.firstElementChild.setAttribute(a.name,a.value);
      if(!player){let b=shapeChoices.get(shape.id);if(!b){b=button('',()=>{selectShape(shape.id);toggleShapeVisibility(shape.id);},'shape-choice');b.addEventListener('dblclick',()=>openPalette(shape.id));const hidden=el('span',null,'shape-hidden-overlay');hidden.append(visibilityIcon(false));b.append(node('svg',{viewBox:'-25 -25 50 50',width:42,height:42}),hidden);shapeChoices.set(shape.id,b);$('shape-list').append(b);}b.setAttribute('aria-pressed',String(shape.visible!==false));b.classList.toggle('shape-selected',shape.id===selected);b.classList.toggle('is-hidden',shape.visible===false);b.setAttribute('aria-label',`${shape.visible===false?'Show':'Hide'} ${shape.type}, ${shape.size} feet`);b.title='Show/hide · Double-click for area options';const visual=JSON.stringify([shape.type,shape.rotation,shape.size,shape.color]);if(b.dataset.visual===visual)continue;b.dataset.visual=visual;const icon=b.firstElementChild,g=node('g',{transform:`translate(0 ${shape.type==='cone'?10:0}) rotate(${shape.rotation}) scale(${shape.type==='circle'?18/shape.size:28/shape.size})`});g.append(footprint(shape,true));icon.replaceChildren(g);}
    }
    if(player)return;const shape=s.shapes.find(v=>v.id===selected);if(!shape)selected=null;if(palette&&!s.shapes.some(v=>v.id===palette.id))closePalette();renderHandles(shape);renderPalette();positionPalette();
  }
  function closePalette(){palette?.root.remove();palette=null;}
  function positionPalette(){if(!palette||!geometry)return;const shape=getState().shapes.find(s=>s.id===palette.id);if(!shape)return;const[x,y]=world(shape.center),{matrix,left,top}=geometry,r=palette.root;r.style.left=`${clamp(matrix.a*x+matrix.c*y+matrix.e-left-r.offsetWidth/2,4,Math.max(4,stage.clientWidth-r.offsetWidth-4))}px`;r.style.top=`${clamp(matrix.b*x+matrix.d*y+matrix.f-top-r.offsetHeight-20,4,Math.max(4,stage.clientHeight-r.offsetHeight-4))}px`;}
  function toggleShapeVisibility(id){const shape=getState().shapes.find(s=>s.id===id);if(shape)commit({...getState(),shapes:getState().shapes.map(s=>s.id===id?{...s,visible:s.visible===false}:s)},'Area visibility updated.');}
  function removeShape(id){closePalette();if(selected===id)selected=null;commit({...getState(),shapes:getState().shapes.filter(s=>s.id!==id)},'Area removed.');}
  function renderPalette(){if(!palette)return;const shape=getState().shapes.find(s=>s.id===palette.id);if(!shape)return;const b=palette.visibility,visible=shape.visible!==false;b.replaceChildren(visibilityIcon(visible));b.setAttribute('aria-label',`${visible?'Hide':'Show'} spell area`);b.title=`${visible?'Hide':'Show'} spell area`;b.setAttribute('aria-pressed',String(visible));for(const swatch of palette.root.querySelectorAll('[data-area-color]'))swatch.setAttribute('aria-pressed',String(swatch.dataset.areaColor===shape.color));}
  function openPalette(id){
    closeStatus();closePalette();selectShape(id);const shape=getState().shapes.find(v=>v.id===id);if(!shape)return;
    const root=el('div',undefined,'shape-palette'),colors=el('div',undefined,'shape-palette-colors');root.setAttribute('role','group');root.setAttribute('aria-label','Spell area options');
    const visibility=button('',()=>toggleShapeVisibility(id),'shape-palette-action shape-visibility'),remove=button('',()=>removeShape(id),'shape-palette-action shape-remove');remove.append(el('span','×'));remove.setAttribute('aria-label','Remove spell area');remove.title='Remove spell area';
    palette={id,root,visibility};SHAPE_COLORS.forEach((color,i)=>{const b=button('',()=>{closePalette();updateShape({color});},'color-swatch');b.style.backgroundColor=color;b.dataset.areaColor=color;b.setAttribute('aria-label',`${names[i]} area`);colors.append(b);});root.append(visibility,colors,remove);renderPalette();stage.append(root);positionPalette();
  }
  function positionSizeLabel(){const s=getState().shapes.find(s=>s.id===selected);sizeLabel.hidden=!s;if(!s||!geometry)return;const b=shapeBounds(s,map),{matrix,left,top}=geometry,bounds={left:matrix.a*b.left+matrix.e-left,right:matrix.a*b.right+matrix.e-left,top:matrix.d*b.top+matrix.f-top};const p=placeShapeLabel(bounds,{width:sizeLabel.offsetWidth,height:sizeLabel.offsetHeight},{width:stage.clientWidth,height:stage.clientHeight});sizeLabel.style.left=`${p.left}px`;sizeLabel.style.top=`${p.top}px`;}
  function renderHandles(s){if(!s){if(!sizeLabel.hidden)sizeLabel.hidden=true;if(overlay.style.display!=='none')overlay.style.display='none';if($('shape-handles').childElementCount)$('shape-handles').replaceChildren();return;}sizeLabel.hidden=false;overlay.setAttribute('viewBox',svg.getAttribute('viewBox'));overlay.style.display=s?'':'none';const layer=$('shape-handles');layer.replaceChildren();if(!s)return;const[x,y]=world(s.center),r=feetToWorld(map,s.size),unit=1/getState().camera.zoom,g=node('g',{'data-shape':s.id,transform:`translate(${x} ${y}) rotate(${s.rotation})`});let handles;
    if(s.type==='circle')handles=[['size',0,-r],['size',r,0],['size',0,r],['size',-r,0]];
    else if(s.type==='square')handles=[['size',-r/2,-r/2],['size',r/2,-r/2],['size',r/2,r/2],['size',-r/2,r/2],['rotate',0,-r/2,0],['rotate',r/2,0,90],['rotate',0,r/2,180],['rotate',-r/2,0,270]];
    else handles=[['rotate',0,0,180],['rotate',0,-r,0],['size',-.5*r,-Math.sqrt(3)/2*r],['size',.5*r,-Math.sqrt(3)/2*r]];
    handles.forEach(([type,hx,hy,angle=0],i)=>{const h=node('g',{'data-handle':type,'data-angle':angle,tabindex:0,role:'button','aria-label':`${type==='rotate'?'Rotate':'Resize'} ${s.type} handle ${i+1}`,'pointer-events':'all',class:'shape-handle'});h.append(node('circle',{cx:hx,cy:hy,r:16*unit,fill:'transparent'}));h.append(type==='rotate'?node('circle',{cx:hx,cy:hy,r:7*unit,fill:'#e8ba71',stroke:'#17251d','stroke-width':2*unit}):node('rect',{x:hx-7*unit,y:hy-7*unit,width:14*unit,height:14*unit,rx:2*unit,fill:'#fff3ce',stroke:'#17251d','stroke-width':2*unit}));g.append(h);});layer.append(g);sizeLabel.textContent=`${s.size} ft ${s.type==='circle'?'radius':s.type==='square'?'side':'cone'}`;positionSizeLabel();}
  const updateShape=patch=>commit({...getState(),shapes:getState().shapes.map(s=>s.id===selected?{...s,...patch}:s)},'Area updated.');
  function closeStatus(){if(!status)return;const{id,draft,root}=status;status=null;root.remove();commit(patchMember(getState(),id,{conditions:draft.conditions,letters:draft.letters,elevation:elevation(draft.elevation),aura:draft.aura}),'Conditions applied.');}
  function positionStatus(){if(!status)return;const token=tokenNodes.get(status.id);if(!token)return;const r=token.getBoundingClientRect(),s=stage.getBoundingClientRect(),root=status.root;root.style.setProperty('--status-max-height',`${stage.clientHeight-8}px`);root.style.left=`${clamp(r.left-s.left+r.width/2-120,4,Math.max(4,s.width-root.offsetWidth-4))}px`;root.style.top=`${clamp(r.top-s.top-50,4,Math.max(4,s.height-root.offsetHeight-4))}px`;}
  function markStatus(){if(!status)return;const {group,index,conditions,letters}=status;for(const[name,root]of [['conditions',conditions],['letters',letters]]){root.classList.toggle('keyboard-active',name===group);[...root.children].forEach((b,i)=>b.classList.toggle('keyboard-choice',name===group&&i===index[name]));}const active=status[group].children[index[group]];active?.focus({preventScroll:true});active?.scrollIntoView({block:'nearest'});}
  function statusKey(e){if(!status||e.isComposing||e.metaKey||e.ctrlKey||e.altKey)return false;const key=e.key,{group,index}=status,root=status[group];if(e.target.closest('.elevation-control,.token-visibility,.aura-colors')&&[' ','Enter'].includes(key))return false;if(['Backspace','Escape','Delete'].includes(key)){e.preventDefault();e.stopImmediatePropagation();closeStatus();return true;}
    if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Enter'].includes(key)||/^[a-z]$/i.test(key)){e.preventDefault();e.stopImmediatePropagation();if(key.startsWith('Arrow'))Object.assign(status,statusCursor(group,index,key,CONDITIONS.length));else if(key===' '||key==='Enter')root.children[index[group]]?.click();else if(group==='letters'){index.letters=key.toUpperCase().charCodeAt(0)-65;lettersClick(index.letters);}else{const matches=CONDITIONS.map((c,i)=>({name:c[2],i})).filter(c=>c.name.toLowerCase().startsWith(key.toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name));if(matches.length){const previous=status.search===key.toLowerCase()?matches.findIndex(c=>c.i===index.conditions):-1;index.conditions=matches[(previous+1)%matches.length].i;}status.search=key.toLowerCase();}markStatus();return true;}return false;
  }
  function lettersClick(index){status?.letters.children[index]?.click();}
  function openStatus(id){closePalette();closeStatus();selected=null;renderShapes();const member=combatants(getState()).find(m=>m.id===id);if(!member)return;if(member.item){editItem(id,true);return;}closeItemComment();itemSelected=null;itemEditing=null;const root=el('div',undefined,'token-status-editor'),letters=el('div',undefined,'letter-options'),conditions=el('div',undefined,'condition-options');root.setAttribute('role','dialog');root.setAttribute('aria-label',`${member.name} conditions`);letters.setAttribute('role','group');letters.setAttribute('aria-label','Letter markers');conditions.setAttribute('role','group');conditions.setAttribute('aria-label','Conditions');const left=el('div',undefined,'status-left');left.append(letters);root.append(left,el('div',undefined,'status-spacer'),conditions);status={id,draft:structuredClone(member),root,letters,conditions,group:'conditions',index:{conditions:0,letters:0}};stage.append(root);
    const toggle=(field,value,b)=>{if(!status)return;const list=status.draft[field];status.draft[field]=list.includes(value)?list.filter(v=>v!==value):[...list,value];b.setAttribute('aria-pressed',status.draft[field].includes(value));status.group=field;status.index[field]=[...b.parentElement.children].indexOf(b);renderCharacters();markStatus();};
    const colors=el('div',undefined,'aura-colors');colors.setAttribute('role','group');colors.setAttribute('aria-label','Aura color');SHAPE_COLORS.forEach((color,i)=>{const b=button('',()=>{if(!status)return;status.draft.aura=status.draft.aura?.color===color?null:{color,range:status.draft.aura?.range||5};for(const v of colors.children)v.setAttribute('aria-pressed',String(status.draft.aura?.color===v.dataset.auraColor));renderCharacters();},'color-swatch');b.dataset.auraColor=color;b.style.backgroundColor=color;b.setAttribute('aria-label',`${names[i]} aura`);b.setAttribute('aria-pressed',String(member.aura?.color===color));colors.append(b);});left.append(colors);
    left.append(elevationControl(()=>status?.draft.elevation||0,value=>{if(status){status.draft.elevation=value;renderCharacters();}}));
    if(member.monster){status.visibility=visibilityButton(id,true);left.append(status.visibility);}
    for(const l of 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'){const b=button(l,()=>toggle('letters',l,b));b.setAttribute('aria-pressed',member.letters.includes(l));letters.append(b);}for(const[id,,name]of CONDITIONS){const b=button('',()=>toggle('conditions',id,b));b.append(conditionIcon(id),el('span',name));b.setAttribute('aria-pressed',member.conditions.includes(id));conditions.append(b);}renderCharacters();positionStatus();markStatus();}
  function visibilityButton(id,compact=false){const b=button('',()=>{const m=combatants(getState()).find(m=>m.id===id);if(m)commit(patchMember(getState(),id,{visible:!m.visible}),'Player visibility updated.');},`token-visibility${compact?' compact':''}`);b.dataset.visibilityFor=id;updateVisibilityButton(b);return b;}
  function updateVisibilityButton(b){if(!b)return;const m=combatants(getState()).find(m=>m.id===b.dataset.visibilityFor);if(!m)return;const visible=m.visible===true;b.setAttribute('aria-pressed',String(visible));b.setAttribute('aria-label',`${visible?'Hide':'Show'} ${m.name} ${visible?'from':'to'} players`);b.replaceChildren(visibilityIcon(visible),el('span',b.classList.contains('compact')?(visible?'Visible':'Hidden'):(visible?'Visible to players':'Hidden from players')));}
  function updateVisibilityControls(){updateVisibilityButton(status?.visibility);updateVisibilityButton(itemComment?.visibility);}
  function elevationControl(get,set){const root=el('div',undefined,'elevation-control'),label=el('span','ft:'),value=el('output',String(get()));const adjust=n=>{const next=elevation(get()+n);set(next);value.value=String(next);};const minus=button('−',()=>adjust(-5)),plus=button('+',()=>adjust(5));minus.setAttribute('aria-label','Lower elevation 5 feet');plus.setAttribute('aria-label','Raise elevation 5 feet');root.append(label,value,minus,plus);return root;}
  function positionItemControls(){
    const token=tokenNodes.get(itemSelected);itemDelete.hidden=itemNotes.hidden=!token||token.hidden||itemEditing!==itemSelected||!!itemComment;
    if(!token||itemDelete.hidden&&!itemComment)return;const r=token.getBoundingClientRect(),s=stage.getBoundingClientRect();itemDelete.style.left=`${clamp(r.left-s.left+r.width/2-32,2,stage.clientWidth-66)}px`;itemDelete.style.top=`${clamp(r.top-s.top>=36?r.top-s.top-36:r.bottom-s.top+6,2,stage.clientHeight-32)}px`;
    itemNotes.style.left=`${parseFloat(itemDelete.style.left)+34}px`;itemNotes.style.top=itemDelete.style.top;
    if(itemComment){const root=itemComment.root;root.style.maxWidth=`${Math.max(1,stage.clientWidth-8)}px`;root.style.maxHeight=`${Math.max(1,stage.clientHeight-8)}px`;root.style.left=`${clamp(r.left-s.left+r.width/2-root.offsetWidth/2,4,Math.max(4,stage.clientWidth-root.offsetWidth-4))}px`;root.style.top=`${clamp(r.bottom-s.top+8,4,Math.max(4,stage.clientHeight-root.offsetHeight-4))}px`;}
  }
  function selectItem(id){if(itemEditing!==id)itemEditing=null;closePalette();if(status)closeStatus();if(itemComment?.id!==id)closeItemComment();selected=null;itemSelected=getState().items.some(m=>m.id===id)?id:null;itemEditing=itemSelected;renderShapes();renderCharacters();}
  function deleteSelectedItem(){if(!itemSelected)return;const id=itemSelected;closeItemComment();itemSelected=null;itemEditing=null;commit({...getState(),items:getState().items.filter(m=>m.id!==id)},'Item removed.');}
  function closeItemComment(){if(!itemComment)return;const {id,root,input,name}=itemComment;itemComment=null;root.remove();const item=getState().items.find(m=>m.id===id),title=name.value.trim().slice(0,32)||'Item',comment=input.value.slice(0,2000);if(item&&(item.comment!==comment||item.name!==title))commit(patchMember(getState(),id,{name:title,comment}),'Item details saved.');positionItemControls();}
  function openItemComment(id){selectItem(id);closeItemComment();const item=getState().items.find(m=>m.id===id);if(!item)return;const root=el('div',undefined,'item-comment'),name=el('input'),input=el('textarea');root.setAttribute('role','dialog');root.setAttribute('aria-label',`${item.name} comment`);name.type='text';name.value=item.name;name.maxLength=32;name.setAttribute('aria-label','Placed item name');input.value=item.comment||'';input.maxLength=2000;input.rows=4;input.setAttribute('aria-label','Item comment');const header=el('header',undefined,'item-editor-actions'),visible=visibilityButton(id),remove=button('×',deleteSelectedItem,'item-editor-delete'),close=button('',()=>{closeItemComment();renderCharacters();},'item-editor-close');remove.setAttribute('aria-label','Delete selected item');close.append(chevronIcon());close.setAttribute('aria-label','Close item comment');header.append(visible,remove,close);root.append(header,name,input,elevationControl(()=>getState().items.find(m=>m.id===id)?.elevation||0,value=>commit(patchMember(getState(),id,{elevation:value}),'Item elevation updated.')));itemEditing=id;itemComment={id,root,input,name,visibility:visible};stage.append(root);positionItemControls();input.focus({preventScroll:true});}
  function editItem(id,notes=false){setTool(null);selectItem(id);itemEditing=itemSelected;renderCharacters();if(notes&&itemSelected)openItemComment(id);}
  function flush(){cancelAnimationFrame(frame);frame=0;if(pending){const p=pending;pending=null;preview(p.state,p.characters);if(p.characters&&performance.now()-lastLive>32){lastLive=performance.now();livePositions?.(typeof p.characters==='string'?p.characters:null);}}}
  function queue(state,characters){pending={state,characters};if(!frame)frame=requestAnimationFrame(flush);}
  if(!player){
    stage.tabIndex=-1;
    document.addEventListener('library-opening',()=>{closeItemComment();itemSelected=null;itemEditing=null;closeStatus();closePalette();renderCharacters();});
    stage.addEventListener('dblclick',e=>{if(getTool()||e.target.closest('.token-status-editor,.shape-palette,.item-comment,.item-delete,.item-notes,.reference-suite'))return;const token=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-character]');if(token){e.preventDefault();e.stopPropagation();openStatus(token.dataset.character);}else{const shape=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-shape]');if(shape){e.preventDefault();e.stopPropagation();openPalette(shape.dataset.shape);}}});
    ['party','players'].forEach(mode=>$(`mode-${mode}`).addEventListener('click',()=>commit(setTokenMode(map,getState(),mode),'Token display updated.')));
    document.querySelectorAll('[data-add-shape]').forEach(b=>b.addEventListener('click',()=>{if(getState().shapes.length>=32)return;setTool(null);const s=getState(),shape=newShape(b.dataset.addShape,[s.camera.x,s.camera.y],crypto.randomUUID());if(s.snap)shape.center=snapPoint(map,shape.center,shape.type==='square'?shape.size:5);selected=shape.id;commit({...s,shapes:[...s.shapes,shape]},'Area added.');}));
    document.addEventListener('pointerdown',e=>{const itemTrigger=e.target.closest('[data-item-edit]');let dismissed=false;if(itemEditing&&!itemTrigger&&!e.target.closest('.item-comment,.item-delete,.item-notes')&&e.target.closest('[data-character]')?.dataset.character!==itemEditing){itemEditing=null;itemSelected=null;renderCharacters();dismissed=true;}if(itemComment&&!itemTrigger&&!itemComment.root.contains(e.target)){closeItemComment();itemEditing=null;itemSelected=null;renderCharacters();dismissed=true;}if(status&&!status.root.contains(e.target)){closeStatus();dismissed=true;}if(palette&&!palette.root.contains(e.target)){closePalette();dismissed=true;}if(dismissed)consumeMapDismissal(e,stage);},true);
    document.addEventListener('keydown',e=>{if(e.defaultPrevented||e.target.closest('.reference-suite')||document.querySelector('dialog[open],.dice-panel:not([hidden])'))return;if(itemComment){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();closeItemComment();}return;}if(itemSelected&&!isTextEntry(e.target)&&!e.metaKey&&!e.ctrlKey&&!e.altKey&&['Backspace','Delete','Escape'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();deleteSelectedItem();return;}if(status){statusKey(e);return;}const action=shortcutAction({key:e.key,typing:isTextEntry(e.target),palette:!!palette,shape:!!selected,meta:e.metaKey,ctrl:e.ctrlKey,alt:e.altKey,shift:e.shiftKey,composing:e.isComposing});if(!['close-palette','delete-shape','clear-shape'].includes(action))return;e.preventDefault();e.stopImmediatePropagation();if(action==='close-palette')closePalette();else if(action==='clear-shape'){selected=null;renderShapes();}else{const id=selected;selected=null;commit({...getState(),shapes:getState().shapes.filter(s=>s.id!==id)},'Area removed.');}},true);
    stage.addEventListener('pointerdown',e=>{if(e.button!==0||getTool()||e.target.closest('.token-status-editor,.shape-palette,.item-comment,.item-delete,.item-notes,.dice-panel,#initiative-overlay,.reference-suite'))return;const character=e.target.closest('[data-character]'),shape=e.target.closest('[data-shape]'),handle=e.target.closest('[data-handle]');if(!character&&!shape){if(itemSelected){itemSelected=null;renderCharacters();}if(selected){selected=null;renderShapes();}return;}e.stopImmediatePropagation();e.preventDefault();stage.focus({preventScroll:true});if(shape){itemSelected=null;selected=shape.dataset.shape;}const point=pointAt(e),start=structuredClone(getState());drag={inverse:svg.getScreenCTM().inverse(),id:e.pointerId,character:character?.dataset.character,shape:shape?.dataset.shape,handle:handle?.dataset.handle,angle:Number(handle?.dataset.angle)||0,start,point,x:e.clientX,y:e.clientY,moved:false};stage.setPointerCapture(e.pointerId);if(character){selected=null;itemSelected=getState().items.some(m=>m.id===character.dataset.character)?character.dataset.character:null;preview(bringToFront(getState(),character.dataset.character),true);character.style.zIndex=String(combatants(getState()).find(m=>m.id===character.dataset.character).stack);renderShapes();}else renderShapes();},true);
    stage.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;e.stopImmediatePropagation();if(!drag.moved&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<1)return;drag.moved=true;if(itemEditing===drag.character){itemEditing=null;renderCharacters();}if(drag.character)tokenNodes.get(drag.character)?.classList.add('is-dragging');const wp=new DOMPoint(e.clientX,e.clientY).matrixTransform(drag.inverse),p=[wp.x/map.width,wp.y/map.height];const state=getState();if(drag.character){const m=combatants(drag.start).find(m=>m.id===drag.character);let position=m.position.map((n,i)=>clamp(n+p[i]-drag.point[i],0,1));if(state.snap)position=snapPoint(map,position,m.size);queue(patchMember(state,m.id,{position}),m.id);}else{const original=drag.start.shapes.find(s=>s.id===drag.shape);let next;if(drag.handle==='rotate'){if(original.type==='cone'&&drag.angle===180){const r=feetToWorld(map,original.size),a=original.rotation*Math.PI/180;const pivot=[original.center[0]+Math.sin(a)*r/map.width,original.center[1]-Math.cos(a)*r/map.height];const angle=Math.atan2((p[1]-pivot[1])*map.height,(p[0]-pivot[0])*map.width)*180/Math.PI-90;next={...original,rotation:(angle+720)%360};}else next=rotateShape(map,original,p,drag.angle);}else if(drag.handle)next=resizeShape(map,original,p);else {let center=original.center.map((n,i)=>clamp(n+p[i]-drag.point[i],0,1));if(state.snap)center=snapPoint(map,center,original.type==='square'?original.size:0);next={...original,center};}queue({...state,shapes:state.shapes.map(s=>s.id===next.id?next:s)},false);}},true);
    stage.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;e.stopImmediatePropagation();flush();const d=drag;drag=null;tokenNodes.get(d.character)?.classList.remove('is-dragging');if(stage.hasPointerCapture(e.pointerId))stage.releasePointerCapture(e.pointerId);if(d.moved&&getState().items.some(m=>m.id===d.character)){const m=getState().items.find(m=>m.id===d.character);preview(patchMember(getState(),m.id,{floor:itemFloorAt(map,getState(),m.position)}),true);}if(!d.moved&&itemSelected===d.character)itemEditing=itemSelected;if(d.moved&&itemSelected===d.character)itemSelected=null;if(d.moved||d.character)finishDrag(d.start,d.character?(d.moved?'Token moved.':'Token selected.'):'Area adjusted.');else render();},true);
    stage.addEventListener('pointercancel',e=>{if(!drag||drag.id!==e.pointerId)return;e.stopImmediatePropagation();const d=drag;drag=null;itemSelected=null;itemEditing=null;pending=null;cancelAnimationFrame(frame);frame=0;tokenNodes.get(d.character)?.classList.remove('is-dragging');preview(d.start);livePositions?.();},true);

  }
  function locateToken(id){const m=combatants(getState()).find(m=>m.id===id);if(m?.item)return;located=id;renderCharacters();if(m&&!m.monster&&getState().tokenMode==='party')document.querySelector('#party-layer')?.classList.add('party-located');}
  if(!player)document.addEventListener('features-changing',()=>{auras.clear();closePalette();closeStatus();closeItemComment();itemSelected=itemEditing=located=null;});
  if(!player)document.addEventListener('pointerdown',event=>{if(!located)return;located=null;for(const t of tokenNodes.values())t.classList.remove('token-located');document.querySelector('#party-layer')?.classList.remove('party-located');consumeMapDismissal(event,stage);},true);
  function render(){if(itemSelected&&!getState().items.some(m=>m.id===itemSelected)){itemSelected=null;itemEditing=null;closeItemComment();}renderCharacters();renderShapes();if(!player){$('mode-party').setAttribute('aria-pressed',getState().tokenMode==='party');$('mode-players').setAttribute('aria-pressed',getState().tokenMode==='players');}}
  return {render,selectItem,editItem,showItemNotes:id=>editItem(id,true),locateToken,renderCamera:view=>{updateGeometry(view);renderHandles(getState().shapes.find(s=>s.id===selected));},renderCharacterPositions:position,renderPartyPosition:positionParty,renderAuras:auras.render,isDragging:()=>!!drag||auras.isDragging(),clearSelection:()=>{auras.clear();selected=null;itemSelected=null;itemEditing=null;closeItemComment();closePalette();if(status)closeStatus();renderShapes();renderCharacters();},closeStatus};
}
