import {isBuildingGlobal} from './building-state.js?v=57';
// Floor artwork shares world coordinates; only placed items are scoped to floors.
export function floorList(place){return place.floors||[];}
export function selectedFloor(place,state){const floors=floorList(place);return floors.find(f=>f.id===state.floors?.[place.id])||floors[0]||null;}
export function placeView(place,state){const floor=selectedFloor(place,state);return floor?{...place,actions:floor.actions,sequence:floor.sequence||[]}:place;}
export function selectFloor(map,state,placeId,floorId){const place=map.places.find(p=>p.id===placeId);if(!place?.floors?.some(f=>f.id===floorId))return state;return {...state,floors:{...state.floors,[placeId]:floorId}};}
export function normalizeFloors(map,value){return Object.fromEntries(map.places.filter(p=>p.floors?.length).map(p=>[p.id,p.floors.some(f=>f.id===value?.[p.id])?value[p.id]:p.floors[0].id]));}
export function validFloors(map,value){return value===undefined||!!value&&typeof value==='object'&&!Array.isArray(value)&&Object.entries(value).every(([id,floor])=>map.places.some(p=>p.id===id&&p.floors?.some(f=>f.id===floor)));}
export function interactionOnFloor(map,state,item){const place=map.places.find(p=>p.id===item.placeId);return isBuildingGlobal(item)||!place?.floors?.length||placeView(place,state).actions.includes(item.id);}
export function validateFloors(map){for(const p of map.places){if(p.floors===undefined)continue;const seen=new Set();if(!Array.isArray(p.floors)||!p.floors.length||p.floors.length>12)throw new Error('Invalid floor plans.');for(const f of p.floors){if(!f||typeof f.id!=='string'||!/^[-a-zA-Z0-9]{1,80}$/.test(f.id)||seen.has(f.id)||typeof f.label!=='string'||!f.label.trim()||f.label.length>48||!Array.isArray(f.actions)||new Set(f.actions).size!==f.actions.length||f.actions.some(id=>!p.actions.includes(id)))throw new Error('Invalid floor plan.');seen.add(f.id);if(f.asset!==undefined&&(!map.art[f.asset]||!map.art[f.asset].startsWith('./')||map.art[f.asset].includes('..')||!Array.isArray(f.polygon)||f.polygon.length<3||f.polygon.some(v=>!Array.isArray(v)||v.length!==2||v.some(n=>!Number.isFinite(n)||n<0||n>1))))throw new Error('Invalid floor artwork.');if(f.sequence!==undefined&&(!Array.isArray(f.sequence)||f.sequence.length>8||f.sequence.some(s=>!s||typeof s.label!=='string'||!s.label||!Array.isArray(s.active)||s.active.some(id=>!f.actions.includes(id)))))throw new Error('Invalid floor options.');}}}

export function pointInPolygon([x,y],points){let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const [ax,ay]=points[i],[bx,by]=points[j];if(Math.abs((x-ax)*(by-ay)-(y-ay)*(bx-ax))<1e-10&&x>=Math.min(ax,bx)&&x<=Math.max(ax,bx)&&y>=Math.min(ay,by)&&y<=Math.max(ay,by))return true;if((ay>y)!==(by>y)&&x<(bx-ax)*(y-ay)/(by-ay)+ax)inside=!inside;}return inside;}
export function itemFloorAt(map,state,position){for(const place of map.places){if(floorList(place).length<2)continue;const floor=selectedFloor(place,state),polygon=floor.polygon||place.footprint||map.interactions.find(i=>i.placeId===place.id&&i.type==='roof')?.polygon;if(polygon&&pointInPolygon(position,polygon))return {placeId:place.id,floorId:floor.id};}return null;}
export function itemOnSelectedFloor(item,state){return !item.floor||state.floors?.[item.floor.placeId]===item.floor.floorId;}
