import {el,button} from './editor-dom.js?v=62';
import {boxCorners,fitBox,resizeBox,containsBox,placeBox,boxPlace} from './custom-places.js?v=82';
import {transformPoint} from './map-orientation.js?v=62';
export function createGridPlaces({places=[],dimensions,screen,world,queue,canvas,dialog,center}){
 let entries=places.map(p=>({id:p.id,name:p.name,box:placeBox(p,dimensions())})),selected=null,expanded=false,drag=null;
 const root=el('div',null,'grid-places'),heading=el('div',null,'grid-places-heading'),name=el('input'),list=el('div',null,'grid-places-list');root.setAttribute('aria-label','Custom Places');name.maxLength=64;name.setAttribute('aria-label','Selected place name');
 const toggle=button('⌄',()=>{expanded=!expanded;render();},'grid-places-toggle');toggle.setAttribute('aria-label','Expand Places');
 const add=button('+ Add Place',()=>{const size=Math.min(...dimensions())*.2;const entry={id:`place-${crypto.randomUUID()}`,name:`Place ${entries.length+1}`,box:fitBox({center:center(),width:size,height:size*.65,angle:0},dimensions())};entries.push(entry);selected=entry.id;render();queue();});
 const remove=button('Remove',()=>{entries=entries.filter(p=>p.id!==selected);selected=null;render();queue();});heading.append(el('span','Places'),name,toggle,add,remove);root.append(heading,list);
 const current=()=>entries.find(p=>p.id===selected);
 function render(){const entry=current();name.disabled=!entry;name.value=entry?.name||'';name.placeholder='Select a place';remove.disabled=!entry;add.disabled=entries.length>=80;toggle.textContent=expanded?'⌃':'⌄';toggle.setAttribute('aria-expanded',String(expanded));list.hidden=!expanded;list.replaceChildren();for(const place of entries){const b=button(place.name||'Place',()=>{selected=place.id;expanded=false;render();queue();});b.setAttribute('aria-pressed',String(place.id===selected));b.dataset.editorPlace=place.id;list.append(b);}if(!entries.length)list.append(el('span','No Places'));}
 name.addEventListener('input',()=>{const entry=current();if(entry){entry.name=name.value;queue();}});name.addEventListener('blur',()=>{const entry=current();if(entry){entry.name=entry.name.trim()||'Place';name.value=entry.name;}});
 function deselect(){if(!selected&&!expanded)return;selected=null;expanded=false;render();queue();}
 function outside(e){if(!root.contains(e.target)&&e.target!==canvas)deselect();}dialog.addEventListener('pointerdown',outside,true);
 function handles(box){const points=boxCorners(box).map(screen);return {points,mids:points.map((p,i)=>p.map((n,k)=>(n+points[(i+1)%4][k])/2))};}
 function hit(p){const entry=current();if(!entry)return null;const {points,mids}=handles(entry.box);const corner=points.findIndex(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<12);if(corner>=0)return {kind:'resize',index:corner};const middle=mids.findIndex(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<12);if(middle>=0)return {kind:'rotate',index:middle};return containsBox(entry.box,world(p))?{kind:'move'}:null;}
 function begin(e,p){if(e.button!==0){deselect();return false;}const target=hit(p);if(!target){deselect();return false;}drag={...target,id:e.pointerId,start:world(p),box:structuredClone(current().box)};canvas.setPointerCapture(e.pointerId);e.preventDefault();return true;}
 function move(e,p){if(!drag)return false;if(e.pointerId!==drag.id)return true;const point=world(p),entry=current();if(!entry)return true;let box=drag.box;if(drag.kind==='move')box={...box,center:box.center.map((n,i)=>n+point[i]-drag.start[i])};else if(drag.kind==='resize')box=resizeBox(box,drag.index,point,{square:e.altKey||e.shiftKey,ratio:e.ctrlKey||e.metaKey});else box={...box,angle:box.angle+Math.atan2(point[1]-box.center[1],point[0]-box.center[0])-Math.atan2(drag.start[1]-box.center[1],drag.start[0]-box.center[0])};entry.box=fitBox(box,dimensions());queue();return true;}
 function end(e){if(drag?.id!==e.pointerId)return false;drag=null;if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId);return true;}
 function draw(c){const entry=current();if(!entry)return;const {points,mids}=handles(entry.box);c.save();c.beginPath();points.forEach((p,i)=>i?c.lineTo(...p):c.moveTo(...p));c.closePath();c.fillStyle='#e8ba7120';c.fill();c.strokeStyle='#e8ba71';c.lineWidth=2;c.stroke();c.fillStyle='#152119';for(const [x,y]of points){c.fillRect(x-5,y-5,10,10);c.strokeRect(x-5,y-5,10,10);}for(const [x,y]of mids){c.beginPath();c.arc(x,y,5,0,Math.PI*2);c.fill();c.stroke();}const [x,y]=screen(entry.box.center);c.font='14px system-ui';c.textAlign='center';c.lineWidth=3;c.strokeStyle='#101710';c.strokeText(entry.name,x,y);c.fillStyle='#fff';c.fillText(entry.name,x,y);c.restore();}
 function orient(op){for(const entry of entries){const footprint=boxCorners(entry.box).map(p=>transformPoint(op.matrix,p).map((n,i)=>n/op.dimensions[i]));entry.box=placeBox({footprint},op.dimensions);}queue();}
 render();return {root,draw,begin,move,end,deselect,orient,cursor:p=>{const h=hit(p);return h?.kind==='resize'?'nwse-resize':h?.kind==='rotate'?'crosshair':h?'move':null;},export:()=>entries.map(p=>boxPlace(p,dimensions()))};
}
