import {registerMenu,openMenu,closeMenu} from './main-menu.js?v=25';
import {el,button} from './combat-ui.js?v=25';
import {ITEMS} from './items-catalog.js?v=25';
import {setFace} from './token-portraits.js?v=25';
import {normalizeItem,syncCampaign,applyItemList,deleteGroup,patchToken} from './combat-state.js?v=25';
import {formation} from './encounter-state.js?v=25';
import {uploadImage} from './local-assets.js?v=25';
const $=id=>document.getElementById(id);
function face(item){const img=el('img');img.alt='';img.width=img.height=40;img.draggable=false;setFace(img,item);return img;}
function field(label,value,change,type='text'){const wrap=el('label',label,'field-label'),input=el('input');input.type=type;input.value=value;input.setAttribute('aria-label',label);input.addEventListener('input',()=>change(input.value));wrap.append(input);return {wrap,input};}
export function createItemsUI({map,getState,commit,announce}){
  let selected=null,itemId=null,signature='';
  const sidebar=el('section',undefined,'items-roster');sidebar.id='items-roster';$('combat-roster').after(sidebar);
  const open=button('Items ⌄',()=>openMenu('items'),'map-picker');open.id='open-items-library';open.setAttribute('aria-haspopup','dialog');document.querySelector('.site-identity').append(open);
  const panel=el('section',undefined,'library-dialog');panel.id='items-dialog';
  const layout=el('div',undefined,'library-layout'),groups=el('section',undefined,'library-groups'),main=el('section',undefined,'library-members');layout.append(groups,main);
  const hint=el('p','','library-save-hint'),error=el('p','','save-error');error.setAttribute('role','alert');
  const footer=el('div',undefined,'dialog-actions'),remove=button('Delete item list',()=>{if(!selected)return;commit(deleteGroup(getState(),'items',selected),'Item list deleted. Undo restores it.');selected=null;itemId=null;renderMenu();},'delete-group'),apply=button('Done',()=>{if(selected&&selected!==getState().campaign.activeItems)commit(applyItemList(getState(),selected),'Item list activated.');closeMenu();},'primary');footer.append(remove,apply);panel.append(error,hint,layout,footer);document.body.append(panel);
  const group=()=>syncCampaign(getState()).campaign.itemLists.find(g=>g.id===selected);
  function edit(fn,redraw=true,groupId=selected){const s=syncCampaign(getState()),lists=s.campaign.itemLists.map(g=>g.id===groupId?fn(g):g);commit({...s,campaign:{...s.campaign,itemLists:lists},...(s.campaign.activeItems===groupId?{items:lists.find(g=>g.id===groupId)?.members||[]}:{})},'Items updated.');if(redraw)renderMenu();else refreshLabels();}
  function refreshLabels(){const s=getState();for(const b of groups.querySelectorAll('[data-item-group]')){const g=s.campaign.itemLists.find(g=>g.id===b.dataset.itemGroup);if(g)b.textContent=`${g.name}${g.id===s.campaign.activeItems?' · Active':''}`;}for(const b of main.querySelectorAll('[data-item-id]')){const item=group()?.members.find(m=>m.id===b.dataset.itemId);if(item)b.lastElementChild.textContent=item.name;}}
  function addItem(picture=0,avatar=null,groupId=selected){const g=getState().campaign.itemLists.find(g=>g.id===groupId);if(!g)return;if(g.members.length>=100){announce('Up to 100 items per list.');return;}const points=formation(map,getState().party,100);itemId=crypto.randomUUID();const item=normalizeItem({id:itemId,name:avatar?'Custom item':ITEMS[picture],portrait:picture,avatar,size:5,visible:false,position:points[g.members.length]||getState().party});edit(g=>({...g,members:[...g.members,item]}),true,groupId);}
  function renderMenu(){const s=syncCampaign(getState());if(!s.campaign.itemLists.some(g=>g.id===selected))selected=s.campaign.activeItems||s.campaign.itemLists[0]?.id||null;const g=group();groups.replaceChildren(el('h3','Item lists'),button('+ New item list',()=>{const s=syncCampaign(getState());if(s.campaign.itemLists.length>=20)return;selected=crypto.randomUUID();itemId=null;commit({...s,campaign:{...s.campaign,itemLists:[...s.campaign.itemLists,{id:selected,name:'Items',members:[]}]}},'Item list created.');renderMenu();}));
    for(const list of s.campaign.itemLists){const b=button(`${list.name}${list.id===s.campaign.activeItems?' · Active':''}`,()=>{selected=list.id;itemId=null;renderMenu();},'library-group');b.dataset.itemGroup=list.id;b.setAttribute('aria-pressed',list.id===selected);groups.append(b);}
    main.replaceChildren();remove.disabled=!g;apply.textContent=!g||s.campaign.activeItems===selected?'Done':'Activate item list';hint.textContent=g&&s.campaign.activeItems===selected?'Changes save and update the active game immediately.':'Changes save to this list. Activate to use these items in the game.';if(!g){main.append(el('p','Create an item list to choose its items.','tool-hint'));return;}
    const naming=field('Item list name',g.name,value=>edit(g=>({...g,name:value.trim().slice(0,48)||'Items'}),false));naming.input.maxLength=48;main.append(naming.wrap);
    if(!g.members.some(m=>m.id===itemId))itemId=g.members[0]?.id;
    const strip=el('div',undefined,'library-member-strip item-member-strip');for(const m of g.members){const b=button('',()=>{itemId=m.id;renderMenu();},'library-member');b.dataset.itemId=m.id;b.setAttribute('aria-pressed',m.id===itemId);b.append(face(m),el('span',m.name));strip.append(b);}main.append(strip);
    if(!g.members.some(m=>m.id===itemId))itemId=g.members[0]?.id;const item=g.members.find(m=>m.id===itemId);
    if(item){const patch=(p,redraw=false)=>edit(g=>({...g,members:g.members.map(m=>m.id===itemId?{...m,...p}:m)}),redraw),fields=el('div',undefined,'member-fields'),name=field('Item name',item.name,value=>patch({name:value.trim().slice(0,32)||'Item'})),size=field('Item size in feet',item.size,value=>patch({size:Math.max(1,Math.min(200,Math.round(Number(value)||1)))}),'number');name.input.maxLength=32;size.input.min=1;size.input.max=200;size.input.step=1;size.input.addEventListener('blur',()=>size.input.value=group()?.members.find(m=>m.id===itemId)?.size||1);fields.append(name.wrap,size.wrap,button('Remove item',()=>edit(g=>({...g,members:g.members.filter(m=>m.id!==itemId)})),'quiet'));main.append(fields);}
    const upload=el('input');upload.type='file';upload.accept='image/png,image/jpeg,image/webp';upload.hidden=true;upload.setAttribute('aria-label','Upload custom item image');upload.addEventListener('input',async()=>{const id=selected;try{const asset=await uploadImage(upload.files[0]);addItem(0,asset.id,id);}catch(e){error.textContent=e.message;}});const tools=el('div',undefined,'item-catalog-heading');tools.append(el('h3','Item catalog'),button('Upload custom item',()=>upload.click()),upload);main.append(tools);
    const catalog=el('div',undefined,'item-catalog');catalog.setAttribute('role','group');catalog.setAttribute('aria-label','100 item pictures');ITEMS.forEach((name,portrait)=>{const b=button('',()=>addItem(portrait),'item-catalog-choice');b.title=name;b.setAttribute('aria-label',`Add ${name}`);b.append(face({item:true,portrait}));catalog.append(b);});main.append(catalog);
  }
  function render(){const s=getState(),g=s.campaign.itemLists.find(g=>g.id===s.campaign.activeItems),sig=JSON.stringify([g?.id,g?.name,(s.items||[]).map(({position,stack,...m})=>m)]);if(sig===signature)return;signature=sig;sidebar.replaceChildren(el('h3',g?.name||'Items'));const grid=el('div',undefined,'item-roster-grid');grid.setAttribute('aria-label','Active items');for(const m of s.items||[]){const row=el('div',undefined,'item-roster-row'),b=button('',()=>{itemId=m.id;selected=getState().campaign.activeItems;openMenu('items');},'roster-portrait');b.setAttribute('aria-label',`Edit item ${m.name}`);b.append(face(m),el('span',m.name));const visible=el('input');visible.type='checkbox';visible.checked=m.visible;visible.title='Visible to players';visible.setAttribute('aria-label',`Show item ${m.name} to players`);visible.addEventListener('change',()=>commit(patchToken(getState(),m.id,{visible:visible.checked}),'Item visibility updated.'));row.append(b,visible);grid.append(row);}sidebar.append(grid);}
  registerMenu('items',panel,{onShow:fresh=>{error.textContent='';if(fresh&&!itemId)selected=getState().campaign.activeItems;renderMenu();}});
  document.addEventListener('edit-item',e=>{itemId=e.detail;selected=getState().campaign.activeItems;openMenu('items');});
  render();return {render};
}
