import {ITEM_CROPS} from './item-crops.js?v=29';
export const ITEMS=[
'Longsword','Dagger','Battle axe','Wooden club','Mace','Spear','Bow','Crossbow','Quiver','Round shield',
'Helmet','Boots','Gloves','Chainmail','Leather armour','Red cloak','Wizard hat','Staff','Spellbook','Wand',
'Red potion','Blue potion','Green potion','Purple potion','Amber potion','Glass vial','Clay flask','Canteen','Poison','Bandages',
'Gold coins','Coin purse','Ruby','Sapphire','Emerald','Ring','Necklace','Crown','Goblet','Statuette',
'Iron key','Key ring','Padlock','Scroll','Sealed letter','Map','Journal','Quill and ink','Seal stamp','Hourglass',
'Treasure chest','Barrel','Crate','Sack','Basket','Backpack','Bedroll','Rope','Ladder','Bear trap',
'Torch','Lantern','Candle','Candle holder','Oil lamp','Campfire','Firewood','Coal','Tinderbox','Brazier',
'Bread','Cheese','Apples','Roast meat','Fish','Mushrooms','Herbs','Grain','Jug','Bowl',
'Hammer','Tongs','Anvil','Pickaxe','Shovel','Saw','Sickle','Pitchfork','Bucket','Handcart',
'Skull','Bones','Antlers','Purple crystal','Dragon egg','Feather','Seashell','Pelt','Sundial','Ritual stone',
"Wooden door closed", "Wooden door open", "Iron door closed", "Iron door open", "Stone door closed", "Stone door open", "Double door closed", "Double door open", "Barn door closed", "Barn door open",
"Trapdoor closed", "Trapdoor open", "Cellar hatch closed", "Cellar hatch open", "Iron grate closed", "Iron grate open", "Portcullis lowered", "Portcullis raised", "Prison gate closed", "Prison gate open",
"Secret bookshelf door", "Secret stone door", "Boarded doorway", "Broken wooden door", "Shattered stone door", "Round hobbit door", "Arched oak door", "Crypt door", "Vault door", "Cave entrance",
"Blue portal", "Red portal", "Green portal", "Purple portal", "Gold portal", "Shadow portal", "Frost portal", "Fire portal", "Vine portal", "Star portal",
"Red curtain closed", "Red curtain open", "Blue curtain closed", "Blue curtain open", "Purple curtain closed", "Purple curtain open", "Burlap curtain", "Torn curtain", "Bead curtain", "Silk screen",
"Wooden chest closed", "Wooden chest open", "Iron chest closed", "Iron chest open", "Golden chest closed", "Golden chest open", "Trapped chest", "Broken chest", "Buried chest", "Jewelry box",
"Stairs down stone", "Stairs up stone", "Stairs down wood", "Stairs up wood", "Spiral staircase", "Ladder down", "Rope ladder", "Rope bridge", "Wooden bridge", "Broken bridge",
"Locked gate", "Garden gate", "Fence section", "Broken fence", "Stone wall", "Cracked wall", "Rubble opening", "Barricade", "Spiked barricade", "Sandbag barrier",
"Lever upright", "Lever lowered", "Floor pressure plate", "Stone button", "Wall switch", "Chain winch", "Rope pulley", "Dungeon wheel", "Pedestal switch", "Runic lock",
"Stone archway", "Ruined archway", "Forest archway", "Tent entrance", "Covered pit", "Open pit", "Spiked pit", "Tunnel opening", "Well opening", "Magic doorway",
"Wooden table", "Round table", "Banquet table", "Writing desk", "Wooden chair", "Armchair", "Wooden bench", "Stone bench", "Throne", "Broken chair",
"Single bed", "Double bed", "Bunk bed", "Straw mattress", "Hammock", "Cradle", "Cot", "Red rug", "Blue rug", "Animal rug",
"Bookshelf", "Empty bookshelf", "Cupboard", "Wardrobe", "Dresser", "Weapon rack", "Armour stand", "Coat rack", "Display cabinet", "Filing chest",
"Fireplace lit", "Fireplace cold", "Stone oven", "Cooking hearth", "Cauldron", "Cooking pot", "Frying pan", "Kettle", "Cutting board", "Mortar and pestle",
"Water barrel", "Wine barrel", "Open barrel", "Broken barrel", "Wooden tub", "Wash basin", "Water pump", "Stone well", "Well bucket", "Water trough",
"Hay bale", "Hay pile", "Grain sack", "Flour sack", "Feed bag", "Wool bundle", "Leather roll", "Cloth roll", "Lumber pile", "Stone pile",
"Wagon", "Broken wagon", "Wheelbarrow", "Cart wheel", "Plough", "Grinding stone", "Millstone", "Loom", "Spinning wheel", "Beehive",
"Horse saddle", "Horseshoe", "Reins", "Yoke", "Bird cage", "Animal cage", "Fish trap", "Fishing net", "Chicken coop", "Rabbit hutch",
"Market stall", "Canvas awning", "Wooden sign", "Hanging sign", "Notice board", "Street post", "Bell", "Hand bell", "Weather vane", "Scales",
"Tent", "Small pavilion", "Canvas tarp", "Bedside table", "Folding stool", "Room divider", "Standing mirror", "Bathtub", "Chamber pot", "Laundry basket",
"Stone altar", "Blood altar", "Holy altar", "Runic altar", "Stone pedestal", "Crystal pedestal", "Shrine", "Prayer wheel", "Incense burner", "Offering bowl",
"Pentagram circle", "Runic circle", "Summoning circle", "Protective circle", "Teleport circle", "Broken magic circle", "Blue rune stone", "Red rune stone", "Green rune stone", "Gold rune stone",
"White crystal", "Black crystal", "Blue crystal", "Red crystal", "Green crystal", "Crystal cluster", "Crystal ball", "Floating orb", "Soul gem", "Glowing geode",
"Coffin closed", "Coffin open", "Stone sarcophagus closed", "Stone sarcophagus open", "Gravestone", "Broken gravestone", "Bone pile", "Skeleton remains", "Skull candle", "Funeral urn",
"Spider web", "Web cocoon", "Giant egg", "Egg clutch", "Monster nest", "Wasp nest", "Rat hole", "Burrow", "Shed snakeskin", "Claw marks",
"Blood pool", "Green slime", "Purple slime", "Black ooze", "Acid puddle", "Oil puddle", "Water puddle", "Ice patch", "Ash pile", "Scorched ground",
"Purple mushroom", "Red mushroom", "Blue mushroom", "Giant mushroom", "Mushroom cluster", "Purple mold", "Green mold", "Poison spores", "Vine knot", "Thorn bush",
"Small boulder", "Large boulder", "Cracked boulder", "Standing stone", "Stalactite", "Stalagmite", "Fallen log", "Tree stump", "Uprooted tree", "Dead tree",
"Campfire cold", "Bonfire", "Fire brazier", "Blue flame brazier", "Smoke plume", "Fog cloud", "Dust cloud", "Steam vent", "Lava vent", "Geyser",
"Statue angel", "Statue warrior", "Statue dragon", "Statue wolf", "Headless statue", "Broken statue", "Gargoyle statue", "Obelisk", "Totem pole", "Scarecrow",
"Rapier", "Scimitar", "Shortsword", "Greatsword", "Hand axe", "Warhammer", "Flail", "Morningstar", "Halberd", "Trident",
"Javelins", "Arrows", "Crossbow bolts", "Sling", "Throwing knives", "Whip", "Net", "Buckler", "Tower shield", "Broken sword",
"Silver coins", "Copper coins", "Treasure pile", "Pearls", "Diamond", "Amethyst", "Opal", "Jade", "Golden bracelet", "Silver locket",
"Holy symbol sun", "Holy symbol moon", "Bone talisman", "Feather charm", "Silver medallion", "Signet ring", "Cursed amulet", "Magic compass", "Magnifying glass", "Spyglass",
"Healing potion", "Mana potion", "Antidote", "Alchemist fire", "Acid flask", "Holy water", "Empty potion bottle", "Perfume bottle", "Salt jar", "Honey jar",
"Open spellbook", "Burned book", "Chained book", "Ancient tablet", "Stone tablet", "Wanted poster", "Torn note", "Rolled parchment", "Open letter", "Leather document case",
"Lockpicks", "Crowbar", "Chisel", "Drill", "Pliers", "Needle and thread", "Scissors", "Paintbrush", "Measuring cord", "Whetstone",
"Lute", "Harp", "Flute", "Drum", "Horn", "Violin", "Panpipes", "Playing cards", "Dice", "Chess board",
"Chains", "Manacles", "Iron shackles", "Ball and chain", "Rope bundle", "Grappling hook", "Caltrops", "Ball bearings", "Hunting snare", "Tripwire",
"Dragon scale", "Dragon tooth", "Unicorn horn", "Phoenix feather", "Dried bat wing", "Monster eye", "Tentacle", "Severed vine", "Fossil", "Meteorite"];
export const ITEM_ATLAS='./assets/items.png';
export const ITEM_ATLASES=[ITEM_ATLAS,'./assets/items-doors.png','./assets/items-furniture.png','./assets/items-scenes.png','./assets/items-equipment.png'];
export function itemAsset(index){const sheet=Math.floor(index/100);return {url:ITEM_ATLASES[sheet],crop:ITEM_CROPS[sheet][index%100].map(value=>value/1254)};}
const synonyms={secret:'hidden concealed passage',door:'entrance doorway gate hatch',portal:'gateway teleport teleportation',curtain:'drape drapery screen',chest:'container treasure coffer box',stairs:'stair staircase steps',trapdoor:'hatch floor entrance',potion:'bottle flask elixir',armour:'armor',mold:'mould fungus fungi blight',mushroom:'fungus fungi',slime:'ooze blight',cage:'prison cell',coffin:'sarcophagus tomb',rug:'carpet',torch:'light fire',lantern:'light lamp'};
export function searchItems(query){const words=String(query).toLowerCase().trim().split(/\s+/).filter(Boolean);return ITEMS.map((name,portrait)=>({name,portrait})).filter(({name})=>{const lower=name.toLowerCase(),terms=lower+' '+Object.entries(synonyms).filter(([key])=>lower.includes(key)).map(([,v])=>v).join(' ');return words.every(word=>terms.includes(word));});}
