import {readRaster,rasterRecord,validImageDimensions} from './image-import.js?v=56';
import {autoSaveEnabled,memoryAsset,rememberAssets,requestMemoryAsset} from './session-storage.js?v=56';
import {assetId} from './combat-state.js?v=56';
let dbPromise;const urls=new Map();
function database(){return dbPromise??=new Promise((resolve,reject)=>{const request=indexedDB.open('ullhexa-local-assets',1);request.onupgradeneeded=()=>request.result.createObjectStore('assets',{keyPath:'id'});request.onsuccess=()=>{const db=request.result;db.onversionchange=()=>{db.close();dbPromise=null;};db.onclose=()=>{dbPromise=null;};resolve(db);};request.onerror=()=>{dbPromise=null;reject(new Error('Local image storage is unavailable.'));};});}
async function storedAsset(id){const db=await database();return new Promise((resolve,reject)=>{const r=db.transaction('assets').objectStore('assets').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
export async function assetRecord(id){const cached=memoryAsset(id);if(cached)return cached;const stored=await storedAsset(id);return stored||await requestMemoryAsset(id);}
export function validAsset(a){return a&&assetId(a.id)&&typeof a.data==='string'&&a.data.length<=128*1024*1024&&/^data:image\/(png|jpeg|webp|avif);base64,[A-Za-z0-9+/]+=*$/.test(a.data)&&validImageDimensions(a.width,a.height)&&(a.framing===undefined||(Number.isFinite(a.framing?.zoom)&&a.framing.zoom>=1&&a.framing.zoom<=5&&[a.framing.x,a.framing.y].every(n=>Number.isFinite(n)&&Math.abs(n)<=5)))&&(a.imageEdit===undefined||(assetId(a.imageEdit?.source)&&a.imageEdit.source!==a.id&&Number.isFinite(a.imageEdit.zoom)&&a.imageEdit.zoom>=1&&a.imageEdit.zoom<=5&&[a.imageEdit.x,a.imageEdit.y].every(n=>Number.isFinite(n)&&Math.abs(n)<=50000)));}
export async function persistAssets(records){if(!records.length)return;if(!records.every(validAsset))throw new Error('Invalid image in this save.');const db=await database();await new Promise((resolve,reject)=>{const tx=db.transaction('assets','readwrite');records.forEach(a=>tx.objectStore('assets').put(a));tx.oncomplete=resolve;tx.onerror=()=>reject(new Error('There is not enough browser storage for these images.'));tx.onabort=tx.onerror;});for(const a of records)urls.delete(a.id);}
export async function putAssets(records){if(!records.every(validAsset))throw new Error('Invalid image in this save.');const saving=autoSaveEnabled();if(saving)await persistAssets(records);rememberAssets(records,{pending:!saving});for(const a of records)urls.delete(a.id);}
export async function assetURL(id){if(!assetId(id))throw new Error('Invalid image reference.');if(!urls.has(id)){const a=await assetRecord(id);if(!a)throw new Error('A local image is missing. Load the original .ullhexa save to restore it.');urls.set(id,a.data);}return urls.get(id);}
export async function uploadImage(file,kind='portrait'){
 const raster=await readRaster(file);try{const record=rasterRecord(raster,{maxSide:kind==='portrait'?256:kind==='stat'?2400:Infinity});await putAssets([record]);return record;}finally{raster.dispose();}
}
export function referencedAssets(value,found=new Set()){if(assetId(value))found.add(value);else if(Array.isArray(value))value.forEach(v=>referencedAssets(v,found));else if(value&&typeof value==='object')Object.values(value).forEach(v=>referencedAssets(v,found));return found;}
export async function exportAssets(value){const all=[],seen=new Set(),pending=[...referencedAssets(value)];while(pending.length){const id=pending.pop();if(seen.has(id))continue;seen.add(id);const a=await assetRecord(id);if(!a)throw new Error('A local image is missing. Restore it before saving.');all.push(a);if(a.imageEdit)pending.push(a.imageEdit.source);}return all;}
export async function clearAssets(){const db=await database();await new Promise((resolve,reject)=>{const tx=db.transaction('assets','readwrite');tx.objectStore('assets').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(new Error('Browser images could not be cleared.'));tx.onabort=tx.onerror;});urls.clear();}
