import {el,button} from './editor-dom.js?v=28';
import {setFace} from './token-portraits.js?v=28';
// Keep tile DOM stable across editor updates so a real double click survives.
export function createMemberStrip({items=false,monster=false,onSelect,onRemove,onStat}){
  const root=el('div',undefined,`library-member-strip${items?' item-member-strip':''}`),nodes=new Map();let selected=null,expanded=null;
  root.addEventListener('keydown',e=>{if(e.key==='Delete'&&!e.metaKey&&!e.ctrlKey&&e.target.closest('.library-member')){e.preventDefault();e.stopPropagation();if(selected)onRemove(selected);}});
  function render(members,id){selected=id;for(const[key,n]of nodes)if(!members.some(m=>m.id===key)){n.remove();nodes.delete(key);}for(const m of members){let wrap=nodes.get(m.id);if(!wrap){wrap=el('div',undefined,'member-tile');const tile=button('',()=>{if(selected!==m.id){onSelect(m.id);tile.focus({preventScroll:true});}},'library-member'),img=el('img'),name=el('span',undefined,'member-name'),remove=button('×',e=>{e.stopPropagation();onRemove(m.id);},'member-remove');img.alt='';img.width=img.height=40;tile.append(img,name);tile.dataset[items?'itemId':'memberId']=m.id;tile.addEventListener('dblclick',e=>{e.preventDefault();expanded=expanded===m.id?null:m.id;for(const [key,n]of nodes)n.classList.toggle('member-expanded',key===expanded);});remove.setAttribute('aria-label',`Remove ${m.name}`);wrap.append(tile,remove);if(monster){const stat=button('',e=>{e.stopPropagation();onStat(m.id);},'member-stat');stat.setAttribute('aria-label',`Edit ${m.name} stat card`);stat.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 2h14v20H5z" fill="currentColor"/><path d="M8 7h8M8 11h8M8 15h8" stroke="#17221d" stroke-width="1.5"/></svg>';wrap.append(stat,el('span',undefined,'stat-card-dot'));}nodes.set(m.id,wrap);}const tile=wrap.firstElementChild;setFace(tile.firstElementChild,m);tile.lastElementChild.textContent=m.name;wrap.querySelector('.member-remove').setAttribute('aria-label',`Remove ${m.name}`);wrap.querySelector('.member-stat')?.setAttribute('aria-label',`Edit ${m.name} stat card`);tile.setAttribute('aria-pressed',m.id===id);wrap.classList.toggle('member-expanded',m.id===expanded);wrap.classList.toggle('has-stat',!!(m.statCard||m.statText));if(wrap.parentElement!==root)root.append(wrap);}return root;}
  return {root,render};
}
