import {el,button} from './editor-dom.js?v=32';
import {assetURL} from './local-assets.js?v=32';
import {loadSpells} from './spell-catalog.js?v=32';
import {findSpells,spellLabel,spellMeta} from './spell-state.js?v=32';
import {patchMember} from './combat-state.js?v=32';
import {consumeMapDismissal} from './map-dismissal.js?v=32';
export function createReferenceViewers({getState,commit,prepare,announce}){
 const stage=document.getElementById('map-stage'),root=el('div',undefined,'reference-suite');root.hidden=true;stage.append(root);new ResizeObserver(()=>root.style.setProperty('--reference-height',`${stage.clientHeight}px`)).observe(stage);let catalog=[],assigned=null,view=null,expanded=false,query='',selected=null,request=0;
 const deck=()=>getState().campaign.spellDecks.find(d=>d.id===getState().campaign.activeSpellDeck),member=()=>getState().roster.find(m=>m.id===assigned);
 const deckButton=button('Spell Deck',()=>showDeck(),'spell-deck-button');deckButton.id='open-spell-deck';const section=el('section',undefined,'tool-section spell-deck-section');section.append(deckButton);document.getElementById('spell-areas').after(section);
 function close(){request++;assigned=null;view=null;root.replaceChildren();root.hidden=true;root.classList.remove('has-assignment','is-expanded');}
 function closeViewer(){view=null;expanded=false;if(assigned)render();else close();}
 async function ensure(){catalog=await loadSpells();}
 async function showDeck(id=null,linked=false){const ticket=++request;try{await ensure();if(ticket!==request)return;prepare();if(!linked)assigned=null;view={kind:'deck'};query='';selected=id||findSpells(catalog,'',deck()?.spells||[])[0]?.id||null;expanded=false;render();}catch(e){announce(e.message);}}
 async function showAssigned(id){const ticket=++request;try{await ensure();if(ticket!==request)return;prepare();assigned=id;view=null;expanded=false;render();}catch(e){announce(e.message);}}
 async function showStat(m){const ticket=++request;if(!m?.statCard&&!m?.statText){announce('Add a stat card in Encounter.');return;}try{const url=m.statCard?await assetURL(m.statCard):null;if(ticket!==request)return;prepare();assigned=null;expanded=false;view={kind:'stat',id:m.id,title:m.name,url,text:m.statText};render();}catch(e){announce(e.message);}}
 function header(title,onClose,{back=false}={}){const h=el('div',undefined,'reference-heading');if(back){const b=button('←',closeViewer);b.setAttribute('aria-label','Back to assigned spells');h.append(b);}const x=button('×',onClose);x.setAttribute('aria-label',`Close ${title}`);h.append(el('h2',title),x);return h;}
 function renderAssigned(){const m=member();if(!m){assigned=null;return;}const panel=el('section',undefined,'reference-panel assigned-spells-panel');panel.setAttribute('aria-label',`${m.name} assigned spells`);panel.append(header(m.name,close));const list=el('div',undefined,'assigned-spell-list');for(const spell of findSpells(catalog,'',m.spells||[])){const b=button(spellLabel(spell),()=>{for(const n of list.children)n.classList.toggle('selected',n===b);},'assigned-spell');b.addEventListener('dblclick',()=>showDeck(spell.id,true));b.dataset.assignedSpell=spell.id;list.append(b);}if(!list.childElementCount)list.append(el('p','No assigned spells.','tool-hint'));panel.append(list);
  const chooser=el('details',undefined,'spell-assignment-picker');chooser.append(el('summary','Assign from deck'));const choices=el('div',undefined,'spell-assignment-choices');for(const spell of findSpells(catalog,'',deck()?.spells||[])){const label=el('label',undefined,'check-label'),check=el('input');check.type='checkbox';check.checked=(m.spells||[]).includes(spell.id);check.setAttribute('aria-label',`Assign ${spell.title} to ${m.name}`);check.addEventListener('change',()=>{const current=member();commit(patchMember(getState(),current.id,{spells:check.checked?[...(current.spells||[]),spell.id]:(current.spells||[]).filter(id=>id!==spell.id)}),'Assigned spells updated.');const wasOpen=chooser.open;render();const next=root.querySelector('.spell-assignment-picker');if(next)next.open=wasOpen;});label.append(check,document.createTextNode(spell.title));choices.append(label);}if(!choices.childElementCount)choices.append(el('p','Active deck is empty.','tool-hint'));chooser.append(choices);panel.append(chooser);root.append(panel);
 }
 function toggleSize(){expanded=!expanded;root.classList.toggle('is-expanded',expanded);root.querySelector('[data-expand]')?.setAttribute('aria-pressed',String(expanded));}
 function render(){root.replaceChildren();root.hidden=false;root.classList.toggle('has-assignment',!!assigned);root.classList.toggle('is-expanded',expanded);if(assigned)renderAssigned();if(!view)return;
  const panel=el('section',undefined,`reference-panel ${view.kind==='deck'?'deck-viewer':'stat-viewer'}`);panel.id=view.kind==='deck'?'spell-deck-viewer':'stat-card-viewer';panel.setAttribute('aria-label',view.kind==='deck'?'Active spell deck':`${view.title} stat card`);const heading=header(view.kind==='deck'?(deck()?.name||'Spell deck'):view.title,closeViewer,{back:!!assigned}),enlarge=button('⤢',toggleSize);enlarge.dataset.expand='';enlarge.setAttribute('aria-label','Double card view size');enlarge.setAttribute('aria-pressed',String(expanded));heading.insertBefore(enlarge,heading.lastChild);panel.append(heading);
  if(view.kind==='stat'){const body=el('div',undefined,'reference-cards stat-view-content');if(view.url){const image=el('img');image.src=view.url;image.alt=`${view.title} stat card`;image.className='reference-card-image';image.addEventListener('click',toggleSize);body.append(image);}else{const text=el('div',view.text,'stat-card-text');text.addEventListener('dblclick',toggleSize);body.append(text);}panel.append(body);root.append(panel);return;}
  const search=el('input');search.type='search';search.value=query;search.placeholder='Search this deck';search.setAttribute('aria-label','Search active spell deck');search.className='spell-search';panel.append(search);const body=el('div',undefined,'deck-viewer-body'),list=el('div',undefined,'deck-spell-list'),cards=el('div',undefined,'reference-cards');body.append(list,cards);panel.append(body);root.append(panel);
  function select(id){selected=id;for(const b of list.children)b.setAttribute('aria-pressed',b.dataset.deckSpell===id);cards.replaceChildren();const spell=catalog.find(s=>s.id===id);if(!spell)return;cards.append(el('h3',spell.title),el('p',spellMeta(spell),'spell-meta'));spell.cards.forEach((card,i)=>{const image=el('img');image.className='reference-card-image';image.src=card.src;image.alt=`${spell.title}, card ${i+1} of ${spell.cards.length}`;image.loading='lazy';image.addEventListener('click',toggleSize);cards.append(image);});cards.scrollTop=0;}
  function filter(){const ids=[...new Set([...(deck()?.spells||[]),...(assigned?(member()?.spells||[]):[])])],spells=findSpells(catalog,query,ids);list.replaceChildren();for(const spell of spells){const b=button('',()=>select(spell.id),'deck-spell');b.dataset.deckSpell=spell.id;b.append(el('span',spell.title),el('small',spellMeta(spell)));list.append(b);}if(!spells.some(s=>s.id===selected))selected=spells[0]?.id||null;select(selected);if(!spells.length)list.append(el('p','No spells.','tool-hint'));}
  search.addEventListener('input',()=>{query=search.value;filter();});filter();
 }
 document.addEventListener('library-opening',close);
 document.addEventListener('pointerdown',e=>{if(root.hidden||root.contains(e.target)||!stage.contains(e.target))return;close();consumeMapDismissal(e,stage);},true);
 root.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();view?closeViewer():close();}else if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key)&&!e.target.matches('input,textarea')){e.preventDefault();e.stopPropagation();const list=[...root.querySelectorAll('[data-deck-spell]')],i=list.findIndex(n=>n.dataset.deckSpell===selected);if(list.length&&['ArrowUp','ArrowDown'].includes(e.key))list[(i+(e.key==='ArrowUp'?-1:1)+list.length)%list.length].click();}});
 return{showDeck,showAssigned,showStat,close};
}
