import {sanitizeState,validPoint,GRID_COLORS,validEnvironment} from './state.js?v=18';
import {PORTRAITS,SHAPE_TYPES,SHAPE_COLORS} from './encounter-state.js?v=18';
import {CONDITIONS,safeId,assetId,parseInitiative} from './combat-state.js?v=18';
import {normalizeFog} from './fog-state.js?v=18';
import {validProject} from './presentation-state.js?v=18';
export const MAX_SAVE_BYTES=64*1024*1024;
const object=v=>v!==null&&typeof v==='object'&&!Array.isArray(v),unique=a=>new Set(a).size===a.length;
const check=(ok,message='This save contains incomplete or invalid game data.')=>{if(!ok)throw new Error(message);};
export function saveFilename(name){let base=String(name).trim().replace(/(?:\.ullhexa)+$/i,'').replace(/[<>:"/\\|?*\x00-\x1f]/g,'-').slice(0,100).replace(/[. ]+$/g,'');if(!base)base='Game save';if(/^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\.|$)/i.test(base))base='_'+base;return base+'.ullhexa';}
export function parseSave(text){check(typeof text==='string'&&new TextEncoder().encode(text).length<=MAX_SAVE_BYTES,'This save is too large. Choose an .ullhexa save under 64 MB.');let d;try{d=JSON.parse(text);}catch{throw new Error('This file is not a readable .ullhexa game save.');}check(object(d)&&d.kind==='ullhexa-map-save','This file is not an Ull Hexa map save.');check([1,2].includes(d.version),'This save uses a newer or unsupported save format.');check(typeof d.name==='string'&&d.name.trim().length>0&&d.name.length<=120);check(typeof d.savedAt==='string'&&Number.isFinite(Date.parse(d.savedAt)));check(object(d.state)&&d.state.format===1&&safeId(d.state.mapId)&&typeof d.state.mapVersion==='string'&&d.state.mapVersion.length<=80);check(d.project===undefined||validProject(d.project),'This save contains invalid session selections.');return d;}
function member(p,monster,modern){if(!(object(p)&&safeId(p.id)&&typeof p.name==='string'&&p.name.trim()&&p.name.length<=32&&Number.isInteger(p.portrait)&&p.portrait>=0&&p.portrait<30&&validPoint(p.position)))return false;if(!modern)return true;
  return (p.avatar==null||assetId(p.avatar))&&(p.initiative===null||typeof p.initiative==='number'&&parseInitiative(p.initiative)!==null)&&Array.isArray(p.conditions)&&unique(p.conditions)&&p.conditions.every(id=>CONDITIONS.some(c=>c[0]===id))&&Array.isArray(p.letters)&&unique(p.letters)&&p.letters.every(l=>/^[A-Z]$/.test(l))&&(!monster||(p.monster===true&&Number.isInteger(p.size)&&p.size>=5&&p.size<=200&&p.size%5===0&&typeof p.visible==='boolean'&&Number.isInteger(p.maxHp)&&p.maxHp>=0&&p.maxHp<=100000&&Number.isInteger(p.hp)&&p.hp>=0&&p.hp<=p.maxHp&&(p.statCard==null||assetId(p.statCard))));
}
export function validCampaign(c){return object(c)&&['parties','encounters'].every((key,i)=>Array.isArray(c[key])&&c[key].length<=20&&unique(c[key].map(g=>g?.id))&&c[key].every(g=>object(g)&&safeId(g.id)&&typeof g.name==='string'&&g.name.trim()&&g.name.length<=48&&Array.isArray(g.members)&&g.members.length<=60&&unique(g.members.map(m=>m.id))&&g.members.every(m=>member(m,i===1,true))))&&c.parties.some(g=>g.id===c.activeParty)&&(c.activeEncounter===null||c.encounters.some(g=>g.id===c.activeEncounter));}
export function restoreSave(map,data){const s=data.state,modern=data.version===2;check(s.mapId===map.id,'This save belongs to a different map.');check(s.mapVersion===map.version||(map.previousVersions||[]).includes(s.mapVersion),'This save needs a map version that is not available here.');check(validPoint(s.party)&&typeof s.grid==='boolean'&&['party','players'].includes(s.tokenMode)&&typeof s.regroupPlayers==='boolean');check(s.gridColor===undefined||GRID_COLORS.includes(s.gridColor));check(s.environment===undefined||validEnvironment(s.environment));check(object(s.camera)&&validPoint([s.camera.x,s.camera.y])&&Number.isFinite(s.camera.zoom)&&s.camera.zoom>=1&&s.camera.zoom<=4);check(Array.isArray(s.active)&&unique(s.active)&&s.active.every(id=>map.interactions.some(i=>i.id===id)));check(Array.isArray(s.roster)&&s.roster.length<=(modern?60:12)&&(modern||s.roster.length>0)&&unique(s.roster.map(m=>m.id))&&s.roster.every(p=>member(p,false,modern)));
  if(modern){check(s.public!==true);check(typeof s.snap==='boolean'&&validCampaign(s.campaign));check(Array.isArray(s.monsters)&&s.monsters.length<=60&&s.monsters.every(m=>member(m,true,true))&&unique([...s.roster,...s.monsters].map(m=>m.id)));check(s.turnId===null||safeId(s.turnId));check(object(s.initiativeOverlay)&&validPoint([s.initiativeOverlay.x,s.initiativeOverlay.y])&&typeof s.initiativeOverlay.visible==='boolean');check(Array.isArray(s.fog)&&normalizeFog(s.fog).length===s.fog.length);}
  check(Array.isArray(s.shapes)&&s.shapes.length<=32&&unique(s.shapes.map(a=>a.id)));const legacyColors=['#e8ba71','#ec6d62','#70bce8','#a98ce5','#78cba2','#ef91be'];
  check(s.shapes.every(a=>object(a)&&safeId(a.id)&&(modern?SHAPE_TYPES:[...SHAPE_TYPES,'triangle']).includes(a.type)&&validPoint(a.center)&&[a.width,a.height].every(n=>Number.isInteger(n)&&n>=1&&n<=(modern?400:200))&&Number.isFinite(a.rotation)&&a.rotation>=0&&a.rotation<360&&(modern?SHAPE_COLORS:[...SHAPE_COLORS,...legacyColors]).includes(a.color)&&typeof a.visible==='boolean'&&(!modern||(Number.isInteger(a.size)&&a.size>=5&&a.size<=200&&a.size%5===0&&a.width===a.height&&a.width===a.size*(a.type==='circle'?2:1)))));
  check(object(data.view)&&(map.places.length?map.places.some(p=>p.id===data.view.selectedPlace):data.view.selectedPlace===null)&&Array.isArray(data.view.ruler)&&data.view.ruler.length<=2&&data.view.ruler.every(validPoint));
  return {state:sanitizeState(map,{...s,revision:0}),view:{selectedPlace:data.view.selectedPlace,ruler:data.view.ruler.map(p=>[...p])},name:data.name};
}
export function serializeSave(map,state,name,view,date=new Date(),project){check(typeof name==='string'&&name.trim().length>0&&name.trim().length<=120,'Enter a name for your save.');check(project===undefined||validProject(project),'The session selections could not be saved.');const data={kind:'ullhexa-map-save',version:2,name:name.trim(),savedAt:date.toISOString(),state:{...sanitizeState(map,state),revision:0},view,...(project?{project}:{})};restoreSave(map,data);return JSON.stringify(data);}
