import {el,button,label} from './editor-dom.js?v=62';
import {showDialog} from './dialogs.js?v=62';
import {assetURL,putAssets} from './local-assets.js?v=97';
import {SPELL_SCHOOLS,MAX_SPELL_PAGES,MAX_SPELL_TEXT} from './user-spells.js?v=79';
import {SPELL_ACCEPT,SPELL_FILE_TYPES,importSpellFiles,renderTypedSpell} from './spell-import.js?v=79';

export function editUserSpell(existing=null){
 const dialog=el('dialog',undefined,'user-spell-editor'),header=el('div',undefined,'reference-heading'),content=el('div',undefined,'user-spell-editor-body'),error=el('p','','save-error'),status=el('p','','spell-import-status'),footer=el('div',undefined,'dialog-actions');
 dialog.setAttribute('aria-label',existing?'Edit spell':'Create spell');error.setAttribute('role','alert');status.setAttribute('role','status');
 const controller=new AbortController();let result=null,mode=existing?.source||'file',pages=existing?.source==='file'?existing.cards.map(c=>({...c})):[],page=0,busy=false,previewTicket=0;
 const title=el('input');title.value=existing?.title||'';title.maxLength=120;title.setAttribute('aria-label','Spell title');title.placeholder='Spell title';
 const level=el('select');level.setAttribute('aria-label','Spell level');for(const [value,text]of [['','Unspecified'],['0','Cantrip'],...Array.from({length:9},(_,i)=>[String(i+1),`Level ${i+1}`])]){const option=el('option',text);option.value=value;level.append(option);}level.value=existing?.level==null?'':String(existing.level);
 const school=el('select');school.setAttribute('aria-label','Spell school');for(const value of ['',...SPELL_SCHOOLS,...(existing?.school&&!SPELL_SCHOOLS.includes(existing.school)?[existing.school]:[])]){const option=el('option',value||'Unspecified');option.value=value;school.append(option);}school.value=existing?.school||'';
 const fields=el('div',undefined,'spell-editor-fields');fields.append(label('Title',title),label('Level',level),label('School',school));
 const tabs=el('div',undefined,'source-tabs'),fileMode=button('PDF / image',()=>{mode='file';render();}),textMode=button('Text',()=>{mode='text';render();text.focus();});tabs.append(fileMode,textMode);
 const text=el('textarea');text.value=existing?.text||'';text.maxLength=MAX_SPELL_TEXT;text.rows=12;text.placeholder='Write the spell here';text.setAttribute('aria-label','Spell text');
 const file=el('input');file.type='file';file.multiple=true;file.accept=SPELL_ACCEPT;file.hidden=true;file.setAttribute('aria-label','Upload spell PDF or images');
 const upload=button('Upload PDF / images',()=>{file.value='';file.click();}),note=el('p',SPELL_FILE_TYPES,'image-types'),preview=el('div',undefined,'spell-import-preview'),image=el('img'),count=el('span'),pager=el('div',undefined,'spell-page-controls');image.alt='Spell card preview';
 const prev=button('←',()=>{page=(page-1+pages.length)%pages.length;showPage();}),next=button('→',()=>{page=(page+1)%pages.length;showPage();}),remove=button('Remove page',()=>{pages.splice(page,1);page=Math.min(page,pages.length-1);render();});prev.setAttribute('aria-label','Previous imported page');next.setAttribute('aria-label','Next imported page');pager.append(prev,count,next,remove);preview.append(image,pager);
 function setBusy(value){busy=value;for(const control of [apply,upload,fileMode,textMode,remove,prev,next,title,level,school,text])control.disabled=value;dialog.setAttribute('aria-busy',String(value));if(!value)prev.disabled=next.disabled=pages.length<2;}
 async function showPage(){const ticket=++previewTicket;count.textContent=`${page+1} / ${pages.length}`;prev.disabled=next.disabled=pages.length<2;image.removeAttribute('src');const current=pages[page];if(!current)return;try{const src=current.record?.data||await assetURL(current.asset);if(ticket===previewTicket&&dialog.isConnected)image.src=src;}catch(e){error.textContent=e.message;}}
 function render(){fileMode.setAttribute('aria-pressed',mode==='file');textMode.setAttribute('aria-pressed',mode==='text');content.replaceChildren();if(mode==='text')content.append(text);else{content.append(note,upload,file);if(pages.length){page=Math.max(0,page);content.append(preview);showPage();}else content.append(el('div','PDF or image cards','stat-image-empty'));}}
 file.addEventListener('change',async()=>{const files=[...file.files];if(!files.length||busy)return;setBusy(true);error.textContent='';try{const records=await importSpellFiles(files,{remaining:MAX_SPELL_PAGES-pages.length,signal:controller.signal,onProgress:value=>status.textContent=value});if(controller.signal.aborted)return;pages.push(...records.map(record=>({asset:record.id,record})));if(!title.value.trim())title.value=files[0].name.replace(/\.[^.]+$/,'').slice(0,120);page=pages.length-records.length;mode='file';status.textContent='';render();}catch(e){if(e.name!=='AbortError')error.textContent=e.message;}finally{if(!controller.signal.aborted)setBusy(false);}});
 const apply=button(existing?'Apply':'Create',async()=>{if(busy)return;error.textContent='';if(!title.value.trim()){error.textContent='Enter a spell title.';title.focus();return;}setBusy(true);try{const values={title:title.value.trim(),level:level.value===''?null:Number(level.value),school:school.value,text:mode==='text'?text.value:''};let records,cards;if(mode==='text'){records=renderTypedSpell(values);cards=records.map(r=>({asset:r.id}));}else{if(!pages.length)throw new Error('Upload a PDF or image first.');records=pages.filter(p=>p.record).map(p=>p.record);cards=pages.map(p=>({asset:p.asset}));}await putAssets(records);if(controller.signal.aborted)return;result={id:existing?.id||`user-spell-${crypto.randomUUID()}`,...values,source:mode,cards};dialog.close();}catch(e){error.textContent=e.message;setBusy(false);}},'primary');
 const cancel=button('Cancel',()=>dialog.close()),close=button('×',()=>dialog.close());close.setAttribute('aria-label','Close spell editor');header.append(el('h2',existing?'Edit spell':'Create spell'),close);footer.append(cancel,apply);dialog.append(header,fields,tabs,content,status,error,footer);document.body.append(dialog);
 return new Promise(resolve=>{dialog.addEventListener('close',()=>{controller.abort();previewTicket++;dialog.remove();resolve(result);},{once:true});render();showDialog(dialog);title.focus();});
}
