import {normalizeUserSpells,validUserSpells} from './user-spells.js?v=79';
const safeId=v=>typeof v==='string'&&/^[-a-zA-Z0-9]{1,80}$/.test(v);
export const normalizeSpells=value=>[...new Set((Array.isArray(value)?value:[]).filter(safeId))].slice(0,500);
export const validSpells=value=>value===undefined||Array.isArray(value)&&value.length<=500&&value.every(safeId)&&new Set(value).size===value.length;
export function normalizeSpellLibrary(campaign){const input=campaign?.spellDecks;const spellDecks=Array.isArray(input)?input.filter(d=>d&&safeId(d.id)).filter((d,i,a)=>a.findIndex(v=>v.id===d.id)===i).slice(0,20).map(d=>({id:d.id,name:typeof d.name==='string'?d.name.trim().slice(0,48)||'Spell deck':'Spell deck',spells:normalizeSpells(d.spells)})):[{id:'spell-deck-default',name:'Spell deck',spells:[]}];return{userSpells:normalizeUserSpells(campaign?.userSpells),spellDecks,activeSpellDeck:campaign?.activeSpellDeck===null?null:spellDecks.some(d=>d.id===campaign?.activeSpellDeck)?campaign.activeSpellDeck:spellDecks[0]?.id||null};}
export function validSpellLibrary(c){if(!validUserSpells(c.userSpells))return false;return c.spellDecks===undefined?c.activeSpellDeck===undefined:Array.isArray(c.spellDecks)&&c.spellDecks.length<=20&&new Set(c.spellDecks.map(d=>d?.id)).size===c.spellDecks.length&&c.spellDecks.every(d=>d&&safeId(d.id)&&typeof d.name==='string'&&d.name.trim()&&d.name.length<=48&&Array.isArray(d.spells)&&validSpells(d.spells))&&(c.activeSpellDeck===null||c.spellDecks.some(d=>d.id===c.activeSpellDeck));}
export const spellOrder=(a,b)=>(a.level??10)-(b.level??10)||a.school.localeCompare(b.school)||a.title.localeCompare(b.title);
export const spellLabel=s=>`${s.title}${s.cards.length>1?` [${s.cards.length}]`:''}`;
export const spellMeta=s=>[s.level==null?'':s.level?`Level ${s.level}`:'Cantrip',s.school].filter(Boolean).join(' · ');
export function findSpells(catalog,query='',ids=null){const words=query.trim().toLowerCase().split(/\s+/).filter(Boolean),allowed=ids?new Set(ids):null;return catalog.filter(s=>(!allowed||allowed.has(s.id))&&words.every(w=>`${s.title} ${spellMeta(s)} ${(s.classes||[]).join(' ')}`.toLowerCase().includes(w))).sort(spellOrder);}
