import {showDialog} from './dialogs.js?v=56';

// Keep this guide aligned with the shipped controls, not tabletop rules.
export const MANUAL_SECTIONS=[
  {id:'start',title:'Getting started',text:[
    'Ull Hexa D&D is a control board for a DM running an in-person game. Prepare maps, a party, encounters, items and spell decks in the six libraries at the top left. The DM controls the rules, story and movement; the board does not enforce attacks, collisions, line of sight or legal moves.',
    'A typical setup: choose a map in Maps, activate a party and an encounter, then open Player Display. Move that window to the TV or projector. Use an extended desktop so players see their window while you retain the control board on your own screen.',
    'The left panel contains Party and Encounter initiative scores, placed Items, Places, Spell areas and Spell Deck. The right panel contains Initiative. Drag either panel divider to change its width; double-click the divider to reset it. A focused divider also supports minus, plus and Home.',
    'Use the map header’s Battle map / Story switch to decide what the players see. The map controls immediately below it handle the camera, grid, lighting, prepared scenes, fog and dice. This manual is independent of the libraries. Select a numbered topic on the left. Up/Left moves to the previous topic and Down/Right to the next, even after clicking the article. Home/End jumps to the first/last topic. Close with ×, Escape or a click outside the window.'
  ]},
  {id:'display',title:'Player display & fullscreen',text:[
    'Player Display ↗ opens a separate, resizable player window. The button turns yellow and its arrow becomes ↙ while a player display is connected. Press it again to close that display. If the browser blocks the window, allow pop-ups for this site and try again.',
    'The display follows the DM’s map, camera, grid, light level and public tokens. DM-only controls, monster HP and stat cards, private item notes and reference windows remain on the control board. Use one DM window per game. Both windows must use the same browser profile on the same computer; this is not remote multiplayer.',
    'Open and position the player window before putting the DM into Full screen. Browsers and operating systems may leave fullscreen when a new window takes focus. The app’s libraries, editors and manual open within the DM page and do not request a fullscreen exit.',
    'On the player window, Full screen shows only the scene. Move the pointer to reveal the exit icon in the top-right corner, or use Escape. The pointer remains visible. Overview fits the whole map without distortion; an image with a different aspect ratio from the screen can leave margins.'
  ]},
  {id:'libraries',title:'Libraries & groups',text:[
    'Maps, Story, Party, Encounter, Items and Spells open the shared library window. Use its top tabs to move between libraries. The left column holds named sessions, parties, encounters, item lists or spell decks. A thick line at a group’s left edge marks the one currently applied to the game. The selection frame shows the group you are editing.',
    'Create and rename groups in the left column. Ctrl/Cmd-click toggles individual groups in a multiple selection; Shift-click selects a range. The footer’s Delete action removes the selected groups. Browsing another group does not activate it.',
    'Party, Encounter and Items have a member strip above the catalog. Select a member to edit its name and settings or change its image. Ctrl/Cmd and Shift also support multiple member selection. Remove deletes selected members; hover a member for its individual ×. Clicking elsewhere clears the selection, while choosing a new image keeps the edited member highlighted.',
    'Factory shows the provided assets. User shows your locally imported assets. Edits are retained as you work; closing a library is not Cancel. Edits to an active group update the board immediately. Use Activate for a different group or Done for the active group. Image and stat-card editors have separate Cancel and Apply/Create controls.'
  ]},
  {id:'maps',title:'Maps & scene preparation',text:[
    'In Maps, click a map thumbnail to inspect its preview, places, scale and interactive features. Add it to a named session and arrange the session sequence. Use selected map applies the chosen map and its staged light level. Reapplying the current map preserves its progress.',
    'The compact Map (i/n) list beside the lighting slider switches between the active session’s prepared maps. Each map retains its own camera, fog, building states and token positions. Party and Encounter groups are shared across the game.',
    'In Battle map mode, applying a map changes what players see. In Story mode, you can prepare another map privately, move its camera, set floors and place tokens while the player display stays on the story scene. Press Battle map when ready. Map-to-map, story-to-story and mode changes use a three-second crossfade.',
    'Prepared maps have authored building controls and lighting. Imported images have the shared grid, tokens, fog, measurement, items and spell areas, but importing an image does not create interactive buildings or local lights.'
  ]},
  {id:'story',title:'Story scenes',text:[
    'Story contains prepared abstract animations and your imported images. Select a scene to preview it, add it to a named session and arrange the sequence. Use scene selects it for play. The Story (i/n) list beside the lighting slider provides quick access to that active sequence.',
    'Selecting a story scene while Battle map is active prepares it without changing the player display. Press Story in the map header to show it. Its green fill indicates Story is active; the red Battle map fill indicates the map is active.',
    'While Story is active, Space advances to the next story in the active sequence. Arrow Up and Down still control initiative. An open dice roller takes priority over these shortcuts; ordinary text fields retain their editing behavior.',
    'Under User, Upload image imports a scene. Edit opens its title and framing controls: position and zoom the image, and click Zoom to fit it. Delete removes the selected user asset. Story images retain their original resolution; framing does not downscale the source.'
  ]},
  {id:'camera',title:'Map navigation & measurement',text:[
    'Right-click and drag to pan the DM map. Ctrl/Cmd plus left-drag works too. Ordinary left-drag moves tokens or selected tools instead of panning. The browser’s right-click menu is suppressed only on the playable map. Camera movement stops at the map edges.',
    'Scroll over the map or use − and + to zoom, up to 300%. Overview fits the complete map. Hold and tilt the joystick beside Dice to pan continuously; farther from its center moves faster. Release to stop.',
    'Ctrl/Cmd plus an arrow key moves the camera by one grid cell. The first press aligns an off-grid camera to the nearest grid position; subsequent presses step through cells, with a final partial step allowed to reach the map edge.',
    'Grid toggles the overlay. The three squares select the map’s grid color, black or white. Snap locks dragged tokens to the grid; without it they move freely. Light–Dark changes the scene lighting; prepared light sources reveal more nearby without calculating character vision.',
    'Measure is the crosshair button. Select it, then drag between two map points to see distance in feet. Use its small × to clear the ruler; Escape while Measure is active clears it and leaves the tool. Measurement is straight-line geometry, not terrain-aware pathfinding or an automatic D&D diagonal rule. Focus under a selected Place eases to that place over two seconds, starting and ending slowly, with the building occupying about 60% of the frame where zoom limits permit; the same button then reads Overview. Manual camera movement returns it to Focus.'
  ]},
  {id:'places',title:'Buildings, floors & map events',text:[
    'The Places list matches the numbered, named markers on the DM map. Selecting a place shows three shared controls: Focus/Overview, Cover/Uncover and Intact/Collapsed. Roof cover and collapse apply to the entire building, independent of the selected floor. You can select the basement while keeping the roof on, then uncover that basement directly. Collapse takes visual priority and retains the stored roof and floor choices for restoration.',
    'Additional options lists all remaining effects for the place. The circle on each effect button identifies its floor. Toggle an effect from any floor to prepare it in advance. It appears when its floor is selected and the building is uncovered and intact. Terrain events, such as a broken bridge, keep their own effect button. Unavailable shared controls are dimmed.',
    'Click the numbered building marker once for three icon buttons matching the shared sidebar controls. Click that marker again or outside the buttons to close them. The building artwork itself does not open controls. Double-click it for a compact Floor, Building and Additional options menu. While this menu is open, edits and camera focus are private to the DM; the sidebar and menu stay linked. Click elsewhere on the map, use × or press Escape to close the menu and publish the prepared view. The dismissal click does not also operate another map element. Opening a main library also closes and applies preparation. The prepared change is one Undo step.',
    'Buildings with multiple floor plans show a range, such as Floors: 0 to 4, followed by the selected floor number and down/up arrows. The ground/first floor is 1; upper floors are 2, 3 and so on. The first basement is 0, the second basement is -1, and deeper basements continue -2, -3. Click arrows, type a whole number, or scroll while the value field is focused. Enter applies typed input. Only available floors can be selected.',
    'Changing floors fades only that building to black and then reveals the new floor, taking three seconds in total on both displays. Players and encounters stay visible and keep their positions. An item placed inside a building belongs to the floor selected when it was placed or moved; players see it only on that floor and only if its visibility is enabled. The DM retains every item. Reduced-motion settings skip the fade.',
    'Represent special doors, clues or one-off events with Items. The board does not automatically stop characters from crossing a broken bridge or a wall; the DM decides what the changed scene means.'
  ]},
  {id:'party',title:'Party & player tokens',text:[
    'In Party, create a party, add players and set their names and portraits. Activate the party to use it. Factory offers the provided portraits; User lets you create and edit custom portraits. A selected member can receive another image by clicking it in the catalog.',
    'The Party/Players control beside Measure chooses one group marker or separate player tokens. Drag tokens to move them. Switching to Party and back to Players preserves the players’ last positions unless the Party marker moved. After it moves, the first player takes its position and others form a tight checkerboard around it.',
    'Click a player’s portrait in the left panel to open assigned spells; click it again to close. Click the name to focus its initiative score. Double-click the name to show a temporary locator around that token on the DM map. Clicking elsewhere clears the locator.',
    'Double-click a token on the map to edit its conditions, letter markers and elevation. These markers do not automatically enforce game rules. Name tags keep a consistent size while tokens themselves scale with map zoom.'
  ]},
  {id:'encounters',title:'Encounters, HP & stat blocks',text:[
    'In Encounter, create a group, add creatures and choose images, names and token sizes. Size is in feet. Current HP is linked to Max HP by default, so entering Max fills both. Use the link toggle to enter Current separately. Damage and healing during play affect Current HP only.',
    'Use the visibility checkbox beside a creature in the left panel, or the visibility button below its alphabet/elevation controls, to show or hide it from players. Visibility changes immediately; unfinished conditions stay private until their menu closes. Hidden creatures remain fully visible to the DM with a black token border; visible creatures have red borders. Fog may still conceal a public token on the player display.',
    'Hover a member in the Encounter library for its paper icon and remove ×. The paper icon opens the stat-card editor with Image or Text options. Position and zoom a stat image, or type the text, then Apply stat card. An assigned card keeps its paper icon visible.',
    'Click an encounter portrait in the left panel or Initiative to open its reference window; click it again to close. The window has Stat block and Spell cards tabs and opens on Stat block. If no card exists, the header’s paper icon opens the editor. Portraits on the left open references at the map’s top-left; Initiative portraits open them at the top-right.',
    'Stat images have an enlarge/compress control and a full-viewport reader. Click the map outside the reference to close it. Clicking a creature’s sidebar name focuses initiative; double-clicking the name locates it on the DM map.'
  ]},
  {id:'initiative',title:'Initiative & combat controls',text:[
    'Enter initiative in the score fields beside Party and Encounter names on the left. Decimal dots and commas are accepted. Enter or Right/Down moves to the next field; Left/Up moves to the previous. Navigation includes both groups and wraps at the ends. Each section’s Reset clears that section’s scores.',
    'The Initiative panel on the right sorts the participating characters. Click a row to choose its turn, use the panel’s up/down arrows, or press Up for previous and Down for next. In Battle map mode Space also advances the turn. The list scrolls to keep the current turn visible. Current players have a yellow selection frame; encounters have a red one.',
    'Choosing an encounter in Initiative focuses its damage/heal amount. Type a number, then Left applies damage or Right applies healing. The sword and healing buttons do the same. The amount clears after use. In this amount field, Up/Down and Space can still change turns.',
    'Click the Initiative title or its checkbox to show/hide the player-order overlay. Players see player order only, not the monster list or private HP. Drag the overlay’s DM preview to position it. The current character’s map name gets a dark background.',
    'Portraits have separate actions from selecting a turn: a player portrait opens assigned spells, while an encounter portrait opens its stat/spell reference window. Typing in ordinary fields, using a modal editor, editing conditions or operating the dice roller takes priority over global turn shortcuts.'
  ]},
  {id:'conditions',title:'Conditions, letters & elevation',text:[
    'Double-click a character token to open the conditions and alphabet menus. Click condition icons or letters to toggle them. Changes remain private while the menu is open and appear on the player display when it closes.',
    'Keyboard focus begins in the conditions list. Up/Down moves through conditions; typing a letter finds a condition beginning with it, cycling matches alphabetically. Enter or Space toggles the highlighted condition.',
    'Left moves from conditions into the alphabet. Arrow keys navigate its letter grid normally; Right beyond the right edge of a row returns to conditions. In the alphabet, typing a letter toggles that marker. Active letters can be pressed again to remove them.',
    'The ft value below the alphabet is elevation. − and + change it by five feet. Zero adds nothing to the token name; positive and negative values appear after the name, for example Player [5ft] or Player [-5ft].',
    'Escape, Backspace, Delete or a map click closes the menu. A map click used to close a popup only closes it: it does not also open building controls or start a map action. Conditions and letters are visual notes, not an automatic rules engine.'
  ]},
  {id:'items',title:'Items & private notes',text:[
    'Use Items to build named lists of reusable templates. Search the Factory catalog by descriptive item names, or create custom User tokens. Each template has a name, an integer Item size (ft) and an optional comment. Included assets are highlighted; selecting an included catalog asset selects that template rather than adding a duplicate.',
    'Activate an item list to put its templates in the black tray below the map. If they overflow, use the expand arrow at the tray’s right. Drag a template onto the map to create a copy; the original remains in the tray so you can place more. Removing a template or list does not remove copies already placed.',
    'Only placed copies appear in the left Items panel. New copies are visible to players by default. Click an item’s sidebar image to toggle visibility. A hidden copy has a dimmed sidebar image, a closed-eye icon and a dimmed name. On the DM map it remains fully opaque; its border is black when concealed and white when public on the selected floor.',
    'Click its sidebar name to select the map copy and show the remove and note buttons. Double-click the name to edit that copy’s name, private comment and elevation. Editing begins in the description field. Copies can have different names and notes. A single click and release on a map item shows its remove and note buttons. Double-click opens the full editor, with player visibility and removal at the top. Dragging moves the copy without opening controls; clicking outside dismisses its controls and clears selection.',
    'Delete or Backspace removes a selected map item; Escape also removes it when its comment editor is closed. While the comment editor is open, Escape returns to its quick actions instead. Use Undo if you remove a copy accidentally. Items placed inside multi-floor buildings are shown to players only on the floor they belong to.'
  ]},
  {id:'areas',title:'Spell areas',text:[
    'Spell areas at the bottom of the left panel adds a circle, square or cone. Adding an area exits Measure and fog tools and returns to normal map controls. All areas are immediately visible to players.',
    'Drag the area to move it and use its handles to resize or rotate it. Circles use a radius, squares an equal side length and cones a tip-to-arc length with a 60-degree spread. Sizes change in five-foot increments; the nearby label shows the measured size. Circles have no rotation handle.',
    'Small colored previews in the left list represent areas already on the map. Click a preview or the area itself to select it. Delete or Backspace removes the selected area.',
    'Double-click an area or its preview to open its color palette over the map. Clicking a color applies it and closes the palette. Clicking outside closes it without a color change. Delete, Backspace or Escape while the palette is open closes the palette first, without deleting the area.'
  ]},
  {id:'fog',title:'Fog & lighting',text:[
    'Brush paints fog; Eraser removes it. Choose a 5, 15 or 30 ft brush and drag on the map. Each has a distinct pointer icon. Select the active tool again to return to ordinary controls. Right-drag can still pan while a fog tool is selected without painting.',
    'Fog starts clear. It is 80% opaque on the DM map, with all tokens visible above it, and fully opaque on the player map. Public tokens under fog are concealed from players. Fog is a manual reveal tool, not automatic line of sight. Undo reverses a completed stroke.',
    'Light–Dark dims the scene continuously. Prepared fire, candle and window light follows the authored room, floor and building state. Destroyed buildings can lose their interior lights. This is atmospheric map lighting and does not calculate each creature’s vision or movement.',
    'An imported map has no authored local lighting sources. You can still adjust its overall darkness and use fog. Lighting and fog settings are kept separately for each map.'
  ]},
  {id:'spells',title:'Spell decks & assigned spells',text:[
    'Spells opens the Spell library. Create a named deck in the left column and add the spells you need. Search by title or spell metadata; the list is sorted by level, school and title. A multipart spell appears once with its card count, such as Spell name [4]. User spell-card uploads are not available.',
    'Double-click a spell in the library to open its card reader. The arrows or Left/Right keys move between cards of that spell; clicking the image advances to the next card. Enlarge/compress and full-viewport controls make small text easier to read.',
    'The Spell Deck button below Spell areas opens the active deck in the map region, with a searchable title list and card preview. Selecting a multipart spell shows all its cards. Click a card to enlarge it.',
    'A player portrait opens that character’s assigned-spell list. An encounter portrait opens Stat block / Spell cards; use Spell cards to assign spells to that creature. Assignments come from the active deck. Double-click an assigned spell to append the deck viewer at that spell; Back returns to assignments. Clicking the portrait again or clicking the map outside closes the reference.',
    'Print deck beside Delete spell deck opens a print document using the original 63.5 × 88.9 mm cards, arranged on A4. Choose 100% / Actual size in the printer dialog. The edge-aligned layout requires borderless A4 to retain the entire card edges; printer scaling changes the physical card size.'
  ]},
  {id:'dice',title:'Dice roller',text:[
    'The die button beside the fog tools opens the roller. Click D4, D6, D8, D10, D20 or D100 to add dice of that type. The count above a type shows how many will be thrown. Throw rolls the selected dice and shows their values and total. Reset clears the selection and results.',
    'D100 uses a pair of ten-sided percentile dice: combine tens and units, with 00 and 0 meaning 100. Each D100 pair counts once in the total. Outcomes use unbiased browser cryptographic random sampling; the animation is decorative and does not determine the values.',
    'With the roller open, Space throws, Backspace resets, and Delete or Escape closes it. Right first selects D4; Left first selects D100. Further Left/Right presses move through die types. Up adds a die of the selected type and Down removes one. Its keyboard highlight fades after five idle seconds.',
    'These shortcuts do not interrupt ordinary text entry. You can fill left-panel score fields while leaving the roller open. Clicking the dice button again or clicking outside the roller on the map closes it; clicking a sidebar does not.'
  ]},
  {id:'imports',title:'Importing & editing images',text:[
    'User libraries accept PNG/APNG, JPEG/JFIF, WebP, AVIF, GIF and BMP. The file must actually decode as a supported raster image; changing its extension does not convert it. Limits are 20 MB per input file, 16,384 pixels per side and 64 megapixels. Animated images become a still frame. SVG and executable document formats are not user imports.',
    'Maps: choose User, then Upload map. The grid alignment editor shows the image in a fixed 16:9 frame. Set whole-number Grid X/Y counts; cells remain square, so changing one also updates the other. Frames (ft), default 5, defines the distance per square and therefore the scale of tokens, areas and measurement.',
    'Left-drag moves the grid, right-drag moves the image, and Ctrl/Cmd plus either drag moves them together. Wheel zoom centers on the pointer. Map zoom fits the whole image at minimum; Grid zoom or the square handles at the editor corners changes cell size. Map/Grid checkboxes temporarily hide either layer. Rotation buttons turn the image 90 degrees and mirror buttons flip it horizontally or vertically. Apply grid completes import even if you plan to hide the gameplay grid.',
    'Party, Encounter and Items: choose User, then Create token. Position and zoom the source inside its circular or square frame, then Create. New token images are reduced to 256 × 256, with a limited-resolution source retained for editing. Maps and Story images keep their source resolution.',
    'Edit reopens a selected user asset’s editor. Cancel leaves the asset unchanged; Apply/Create keeps the edits. Delete token removes a selected image from the User catalog; Remove above the member strip removes a member from its group. Already assigned or placed copies are separate from catalog entries.',
    'Imports stay in this browser and game, rather than being uploaded to a shared server. Save game includes the referenced local images so another browser or computer can restore them with the .ullhexa file.'
  ]},
  {id:'saving',title:'Saving, loading & initialization',text:[
    'With Auto save checked, progress and imported assets are retained in this browser. Auto save is independent of downloading a game file. Browser storage is local to the current profile and site; clearing it removes the stored games and imports.',
    'With Auto save off, the board still works and keeps edits while the DM page remains open, including switches between maps. Reloading or closing that page ends temporary changes; the previously saved version remains available. Save game can still export the current temporary game.',
    'Save game downloads a named .ullhexa file containing the prepared maps, story selections, groups, spell assignments, map progress and referenced imported images. Where supported, the browser lets you choose the destination; otherwise its normal download settings apply. Large images make the save larger; Load game accepts files under 64 MB. Load game restores a chosen .ullhexa file into the board.',
    'Keep a downloaded save before moving browsers or clearing storage. Save files are not named or formatted differently for each map. Saving is not required to keep an open temporary game functional.',
    'Initialize Control Board asks you to confirm before resetting this app’s saved games, uploaded assets and panel preferences in the browser. Cancel leaves them alone. Initialize starts a fresh session and resets connected displays. It does not delete downloaded .ullhexa files or unrelated website storage.'
  ]},
  {id:'shortcuts',title:'Keyboard & quick reference',text:[
    'Outside text fields and editors: Ctrl/Cmd+Z undoes; Ctrl/Cmd+Shift+Z or Ctrl+Y redoes. The left/right arrow buttons in the map toolbar do the same. A new gameplay edit clears redo. Undo history is temporary and is not a replacement for a saved game.',
    'Initiative: Down or Space advances, Up goes back. In Story mode, Space advances the story instead. In left-panel score fields, Enter/Right/Down goes to the next player or encounter; Left/Up goes to the previous, wrapping through the list. In an encounter damage/heal field, Left damages and Right heals.',
    'Camera: right-drag or Ctrl/Cmd+left-drag pans; Ctrl/Cmd+arrows steps the camera on the grid. Click a building marker for quick controls; double-click it to prepare a private view. Right-drag remains camera navigation.',
    'Spell areas: Delete/Backspace removes the selected area. If its color menu is open, Delete/Backspace/Escape only closes that menu. Escape otherwise clears the area selection. Selected items: Delete/Backspace/Escape removes the copy unless its note editor is open, where Escape closes the editor.',
    'Dice open: Space throws, Backspace resets, Delete/Escape closes; Left/Right chooses a die type and Up/Down adjusts its count. Conditions open: arrows navigate, letters find conditions or toggle alphabet markers, Enter/Space toggles, and Escape/Backspace/Delete closes.',
    'Libraries: Ctrl/Cmd-click selects multiple groups or members; Shift-click selects a range. Ordinary typing fields retain normal editing except the score and HP shortcuts described above. Escape closes a manual or modal editor; Cancel in an image/stat editor discards that editor’s pending changes.'
  ]},
  {id:'troubleshooting',title:'Troubleshooting',text:[
    'No player window: allow pop-ups for the site, then press Player Display again. Use the same browser profile for both displays and an extended desktop. A separate computer, incognito window or different browser will not join the local session.',
    'Unexpected player scene: check Battle map / Story, the selected Map or Story sequence entry, the current building floor, token visibility and fog. The DM retains concealed tokens and private preparation even when the player display is showing something else.',
    'An image will not import: check its real format, file size and pixel dimensions. JPEG files are supported; a size or decoding error is different from an unsupported extension. Re-export a damaged or unsupported source into PNG, JPEG or WebP. Map and story imports are not automatically downscaled.',
    'A key does something unexpected: check whether you are typing, operating dice, editing conditions or inside a dialog. Those contexts have their own shortcuts. Close that window or finish the field to resume normal gameplay controls.',
    'A temporary game disappeared after refresh: Auto save was off. Load a downloaded .ullhexa save if you made one, or return to the last browser-saved version. Browser data cannot be recovered by this app after it has been cleared. For routine play, keep Auto save on and download a save before ending the session.'
  ]}
];

export function createUserManual(){
  const dialog=document.createElement('dialog');dialog.id='user-manual';dialog.setAttribute('aria-labelledby','manual-title');
  const header=document.createElement('div');header.className='manual-header';const title=document.createElement('h2');title.id='manual-title';title.textContent='User manual';const close=document.createElement('button');close.type='button';close.className='quiet';close.textContent='×';close.setAttribute('aria-label','Close user manual');close.addEventListener('click',()=>dialog.close());header.append(title,close);
  const layout=document.createElement('div');layout.className='manual-layout';const nav=document.createElement('nav');nav.className='manual-topics';nav.setAttribute('aria-label','Manual sections');const article=document.createElement('article');article.className='manual-content';article.tabIndex=0;article.setAttribute('aria-labelledby','manual-section-title');layout.append(nav,article);dialog.append(header,layout);document.body.append(dialog);
  let selected=MANUAL_SECTIONS[0].id;
  function select(section){selected=section.id;for(const button of nav.children){if(button.dataset.section===selected)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current');}const h=document.createElement('h2');h.id='manual-section-title';h.textContent=section.title;article.replaceChildren(h);for(const text of section.text){const p=document.createElement('p');p.textContent=text;article.append(p);}article.scrollTop=0;}
  for(const [index,section] of MANUAL_SECTIONS.entries()){
    const button=document.createElement('button');button.type='button';button.dataset.section=section.id;
    const number=document.createElement('span');number.className='manual-topic-number';number.textContent=`${index+1}.`;
    const label=document.createElement('span');label.className='manual-topic-label';label.textContent=section.title;
    button.append(number,document.createTextNode(' '),label);button.addEventListener('click',()=>select(section));nav.append(button);
  }
  dialog.addEventListener('keydown',e=>{
    if(e.isComposing||e.ctrlKey||e.metaKey||e.altKey||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;
    e.preventDefault();e.stopPropagation();
    const focused=e.target.closest('.manual-topics button')?.dataset.section;
    const i=MANUAL_SECTIONS.findIndex(section=>section.id===(focused||selected)),delta=['ArrowDown','ArrowRight'].includes(e.key)?1:-1;
    const n=e.key==='Home'?0:e.key==='End'?MANUAL_SECTIONS.length-1:(i+delta+MANUAL_SECTIONS.length)%MANUAL_SECTIONS.length;
    select(MANUAL_SECTIONS[n]);nav.children[n].focus({preventScroll:true});nav.children[n].scrollIntoView({block:'nearest',inline:'nearest'});
  });
  select(MANUAL_SECTIONS[0]);
  document.getElementById('open-manual').addEventListener('click',()=>{document.dispatchEvent(new Event('library-opening'));showDialog(dialog,{dismissOnBackdrop:true});nav.querySelector(`[data-section="${selected}"]`).focus({preventScroll:true});});
}
